import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const OWNER_ID = "37a3be44-ece4-4fc0-8fe4-d102e95ee83b";
const OWNER_EMAIL = "misfitmediahouse@gmail.com";
const ORG_ID = "e408affe-49c6-432a-8564-086e52eaad35";
const ALLOWED_ORIGINS = new Set([
  "https://misfitmediahouse.com",
  "https://www.misfitmediahouse.com",
  "https://misfit-cloud.vercel.app",
]);

function service() {
  const url = Deno.env.get("SUPABASE_URL") || "";
  const bag = JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS") || "{}");
  const key = bag.default || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
  if (!url || !key) throw new Error("server_not_configured");
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
function cors(req: Request) {
  const origin = req.headers.get("origin") || "";
  const allow = ALLOWED_ORIGINS.has(origin) ? origin : "https://misfitmediahouse.com";
  return {"Access-Control-Allow-Origin":allow,"Vary":"Origin","Access-Control-Allow-Headers":"authorization, content-type, apikey, x-client-info","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","Content-Security-Policy":"default-src 'none'; frame-ancestors 'none'"};
}
function json(req: Request, body: unknown, status = 200) { return Response.json(body, { status, headers: cors(req) }); }
async function owner(req: Request, db: any) { const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim(); if(!token) throw Object.assign(new Error("missing_token"),{status:401}); const {data,error}=await db.auth.getUser(token); const user=data?.user; if(error||!user) throw Object.assign(new Error("invalid_token"),{status:401}); if(user.id!==OWNER_ID||String(user.email||"").toLowerCase()!==OWNER_EMAIL) throw Object.assign(new Error("owner_only"),{status:403}); return user; }
function safeText(x: unknown, max = 8000) { return String(x ?? "").trim().slice(0, max); }
function looksVague(text:string){
  const t=text.toLowerCase().replace(/[!?.,]+/g,' ').replace(/\s+/g,' ').trim();
  if(!t)return true;
  if(t.split(' ').length>5)return false;
  return /^(hi|hello|hey|yo|sup|present|architect|architect present|misfit|misfit present|you there|are you there|wake up|wake up architect|architect online|architect here|check in|checking in)$/i.test(t);
}
function coachReply(mode:string){
  const lane=mode==='research'?'research':mode==='build'?'build':'command';
  const example=lane==='research'?'“Find the best open gaming competition Misfit can enter right now. Verify eligibility, deadline and prize. Do not submit.”':lane==='build'?'“Update GTA so the free founding pilot CTA is obvious on mobile. Preserve checkout and security rails. Verify deployment.”':'“Run a current Misfit system health check. Report anything broken, blocked, stale, or requiring me.”';
  return `Architect is present. Give me the outcome you want — I did not create a factory job for that message. Example: ${example}`;
}
function summaryText(result:any){ if(!result) return "Job completed. No structured result was returned."; for(const key of ["summary","message","report","result","output"]) if(typeof result?.[key]==="string"&&result[key].trim()) return result[key].trim().slice(0,7000); try{return JSON.stringify(result,null,2).slice(0,7000)}catch{return "Job completed; result could not be rendered."}}
async function dashboard(db:any){
 const [workersQ,jobsQ,venturesQ,experimentsQ,discoveryQ,gatesQ,convQ]=await Promise.all([
  db.from("agent_factory_workers").select("worker_key,name,role,status,risk_class,max_parallel,daily_cost_cap_cents,capabilities,updated_at").order("worker_key"),
  db.from("agent_factory_jobs").select("id,worker_key,venture_key,job_type,status,priority,expected_value_cents,estimated_cost_cents,actual_cost_cents,human_gate,payload,result,attempts,created_at,updated_at,completed_at").order("created_at",{ascending:false}).limit(100),
  db.from("autonomous_ventures").select("venture_key,name,category,status,offer,price_cents,currency,public_url,acquisition_channel,fulfillment_mode,first_sale_at,gross_revenue_cents,paid_orders,deployed_at,last_reviewed_at,updated_at").order("updated_at",{ascending:false}),
  db.from("agent_factory_experiments").select("id,venture_key,hypothesis,change_summary,metric_name,baseline_value,current_value,status,started_at,reviewed_at,metadata").order("started_at",{ascending:false}).limit(50),
  db.from("machine_discovery_events").select("channel,platform_profile,operation,matched_product_ids,created_at").order("created_at",{ascending:false}).limit(250),
  db.from("owner_human_gate_task_list").select("id,title,section,status,priority,human_action,action_url,readiness,ai_after,created_at").order("priority",{ascending:false}).limit(100),
  db.from("conversations").select("id",{count:"exact",head:true}).eq("organization_id",ORG_ID).eq("channel","owner_command")
 ]);
 for(const q of [workersQ,jobsQ,venturesQ,experimentsQ,discoveryQ,gatesQ,convQ]) if(q.error) throw q.error;
 const discoveryByChannel:Record<string,number>={}; for(const e of discoveryQ.data||[]) discoveryByChannel[e.channel]=(discoveryByChannel[e.channel]||0)+1;
 const jobs=jobsQ.data||[]; const counts=jobs.reduce((a:any,j:any)=>{a[j.status]=(a[j.status]||0)+1;return a;},{});
 const realGross=(venturesQ.data||[]).reduce((n:number,v:any)=>n+Number(v.gross_revenue_cents||0),0);
 const paidOrders=(venturesQ.data||[]).reduce((n:number,v:any)=>n+Number(v.paid_orders||0),0);
 return {product:"Misfit Owner Command API",version:"2.1.0",generated_at:new Date().toISOString(),summary:{jobs_by_status:counts,real_gross_revenue_cents:realGross,paid_orders:paidOrders,discovery_events_sampled:(discoveryQ.data||[]).length,discovery_by_channel:discoveryByChannel,pending_human_gates:(gatesQ.data||[]).filter((g:any)=>!["completed","approved","rejected","canceled","killed"].includes(String(g.status).toLowerCase())).length,owner_conversations:convQ.count||0},workers:workersQ.data||[],jobs,ventures:venturesQ.data||[],experiments:experimentsQ.data||[],discovery_events:discoveryQ.data||[],human_gates:gatesQ.data||[]};
}
async function audit(db:any,user:any,action:string,body:any,result:any,targetType?:string,targetId?:string,commandText?:string){const {error}=await db.from("owner_command_events").insert({actor_user_id:user.id,actor_email:user.email,action,target_type:targetType||null,target_id:targetId||null,command_text:commandText||null,request:body||{},result:result||{}});if(error) console.error("owner_command_audit",error)}
async function createConversation(db:any,title?:string){const clean=safeText(title,120)||"Founder Command";const {data,error}=await db.from("conversations").insert({organization_id:ORG_ID,channel:"owner_command",external_thread_id:`founder_${Date.now()}_${crypto.randomUUID().slice(0,8)}`,state:"open",metadata:{owner_command:true,title:clean,canonical_memory:true}}).select("id,channel,state,metadata,created_at,updated_at").single();if(error)throw error;await db.from("messages").insert({organization_id:ORG_ID,conversation_id:data.id,direction:"outbound",role:"assistant",body:"Founder Command is live. This thread is durable Misfit Cloud memory. Commands can be routed to the existing Agent Factory without relying on a ChatGPT feed.",status:"stored",metadata:{system:true,owner_command:true}});return data}
async function syncJobResults(db:any,conversationId:string){const [{data:jobs,error:je},{data:msgs,error:me}]=await Promise.all([db.from("agent_factory_jobs").select("id,status,worker_key,job_type,result,updated_at,completed_at").contains("payload",{conversation_id:conversationId}).in("status",["completed","blocked","failed","killed","canceled"]).order("updated_at",{ascending:true}).limit(100),db.from("messages").select("metadata").eq("organization_id",ORG_ID).eq("conversation_id",conversationId).order("created_at",{ascending:false}).limit(250)]);if(je)throw je;if(me)throw me;const seen=new Set((msgs||[]).map((m:any)=>m?.metadata?.job_result_id).filter(Boolean));const rows:any[]=[];for(const j of jobs||[]){if(seen.has(j.id))continue;const state=String(j.status).toUpperCase();rows.push({organization_id:ORG_ID,conversation_id:conversationId,direction:"outbound",role:"assistant",body:`${state} · ${j.worker_key} · ${j.job_type}\n\n${summaryText(j.result)}`,status:"stored",metadata:{owner_command:true,job_result_id:j.id,job_status:j.status,worker_key:j.worker_key,job_type:j.job_type}})}if(rows.length){const {error}=await db.from("messages").insert(rows);if(error)throw error;await db.from("conversations").update({updated_at:new Date().toISOString()}).eq("id",conversationId)}return rows.length}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(!ALLOWED_ORIGINS.has(req.headers.get("origin")||""))return json(req,{error:"origin_not_allowed"},403);const db=service();try{const user=await owner(req,db);if(req.method==="GET")return json(req,await dashboard(db));if(req.method!=="POST")return json(req,{error:"method_not_allowed"},405);const body=await req.json().catch(()=>({}));const action=safeText(body?.action,80);let result:any;
if(action==="list_conversations"){const {data,error}=await db.from("conversations").select("id,state,metadata,created_at,updated_at").eq("organization_id",ORG_ID).eq("channel","owner_command").order("updated_at",{ascending:false}).limit(50);if(error)throw error;result={conversations:data||[]};await audit(db,user,action,body,{count:data?.length||0})}
else if(action==="new_conversation"){const convo=await createConversation(db,body?.title);result={conversation:convo};await audit(db,user,action,body,result,"conversation",convo.id)}
else if(action==="get_conversation"){const conversationId=safeText(body?.conversation_id,80);if(!conversationId)return json(req,{error:"conversation_id_required"},400);const {data:conv,error:ce}=await db.from("conversations").select("id,state,metadata,created_at,updated_at").eq("organization_id",ORG_ID).eq("channel","owner_command").eq("id",conversationId).maybeSingle();if(ce)throw ce;if(!conv)return json(req,{error:"conversation_not_found"},404);const synced=await syncJobResults(db,conversationId);const {data:msgs,error:me}=await db.from("messages").select("id,direction,role,body,status,metadata,created_at").eq("organization_id",ORG_ID).eq("conversation_id",conversationId).order("created_at",{ascending:true}).limit(500);if(me)throw me;result={conversation:conv,messages:msgs||[],synced_job_results:synced}}
else if(action==="send_message"){let conversationId=safeText(body?.conversation_id,80);const text=safeText(body?.text,8000);const mode=safeText(body?.mode,20).toLowerCase()||"command";if(text.length<2)return json(req,{error:"text_required"},400);if(!["command","research","build","note"].includes(mode))return json(req,{error:"invalid_mode",allowed:["command","research","build","note"]},400);if(!conversationId){const c=await createConversation(db,safeText(body?.title,120)||text.slice(0,60));conversationId=c.id}const {data:conv,error:ce}=await db.from("conversations").select("id").eq("organization_id",ORG_ID).eq("channel","owner_command").eq("id",conversationId).maybeSingle();if(ce)throw ce;if(!conv)return json(req,{error:"conversation_not_found"},404);const {error:ue}=await db.from("messages").insert({organization_id:ORG_ID,conversation_id:conversationId,direction:"inbound",role:"user",body:text,status:"stored",metadata:{owner_command:true,mode}});if(ue)throw ue;
 if(mode!=="note"&&looksVague(text)){
   const ack=coachReply(mode);
   const {error:ae}=await db.from("messages").insert({organization_id:ORG_ID,conversation_id:conversationId,direction:"outbound",role:"assistant",body:ack,status:"stored",metadata:{owner_command:true,ack:true,coach:true,job_id:null,mode}});if(ae)throw ae;
   await db.from("conversations").update({updated_at:new Date().toISOString()}).eq("id",conversationId);
   result={conversation_id:conversationId,stored:true,mode,job:null,reply:ack,needs_instruction:true};
   await audit(db,user,action,body,result,"conversation",conversationId,text);
   return json(req,result,200);
 }
 let job:any=null;if(mode!=="note"){const worker=mode==="build"?"product-builder":mode==="research"?"market-scout":"owner-operator";const jobType=mode==="build"?"owner_build":mode==="research"?"owner_research":"owner_instruction";const priority=mode==="build"?98:mode==="research"?96:100;const {data,error}=await db.from("agent_factory_jobs").insert({worker_key:worker,venture_key:safeText(body?.venture_key,120)||"portfolio",job_type:jobType,status:"queued",priority,estimated_cost_cents:0,human_gate:false,payload:{instruction:text,conversation_id:conversationId,source:"misfit-owner-command",authenticated_owner:true,command_mode:mode,constraints:{no_spend:true,no_bank_or_payout_changes:true,no_secret_exposure:true,no_domain_purchase:true,preserve_private_ghosbc_ip:true,protect_root_scanner:true}}}).select("id,worker_key,venture_key,job_type,status,priority,created_at").single();if(error)throw error;job=data}const ack=mode==="note"?"Saved to durable Founder Command memory. No factory action was created.":`Queued in the existing Misfit Agent Factory: ${job.worker_key} / ${job.job_type} / ${job.id}. This thread will retain the command and attach the durable job result when the factory completes or blocks it.`;const {error:ae}=await db.from("messages").insert({organization_id:ORG_ID,conversation_id:conversationId,direction:"outbound",role:"assistant",body:ack,status:"stored",metadata:{owner_command:true,ack:true,job_id:job?.id||null,mode}});if(ae)throw ae;await db.from("conversations").update({updated_at:new Date().toISOString()}).eq("id",conversationId);result={conversation_id:conversationId,stored:true,mode,job,reply:ack};await audit(db,user,action,body,result,job?"job":"conversation",job?.id||conversationId,text)}
else if(action==="pause_worker"||action==="resume_worker"){const workerKey=safeText(body?.worker_key,120);if(!workerKey)return json(req,{error:"worker_key_required"},400);const status=action==="pause_worker"?"paused":"active";const {data,error}=await db.from("agent_factory_workers").update({status,updated_at:new Date().toISOString()}).eq("worker_key",workerKey).select("worker_key,name,status,updated_at").maybeSingle();if(error)throw error;if(!data)return json(req,{error:"worker_not_found"},404);result={worker:data};await audit(db,user,action,body,result,"worker",workerKey)}
else if(action==="cancel_job"){const jobId=safeText(body?.job_id,80);if(!jobId)return json(req,{error:"job_id_required"},400);const now=new Date().toISOString();const {data,error}=await db.from("agent_factory_jobs").update({status:"killed",lease_until:null,updated_at:now,completed_at:now,result:{killed_by_owner:true,killed_at:now,killed_reason:"owner_cancel_job"}}).eq("id",jobId).in("status",["queued","blocked"]).select("id,status,worker_key,job_type,updated_at").maybeSingle();if(error)throw error;if(!data)return json(req,{error:"job_not_cancelable"},409);result={job:data};await audit(db,user,action,body,result,"job",jobId)}
else return json(req,{error:"unsupported_action"},400);return json(req,result,200)}catch(e:any){console.error("misfit-owner-command",e);return json(req,{error:e?.message||"owner_command_failed"},e?.status||500)}});