import { useState } from 'react';
import Navbar from '../components/Navbar.jsx';
import Footer from '../components/Footer.jsx';

const weights=[['Capability fit','30%'],['Verified quality','20%'],['Cost efficiency','15%'],['Reliability','10%'],['Latency','10%'],['Safety / governance','10%'],['Reputation','5%']];
const hard=['Required capability + protocol compatibility','Policy and safety fit','Availability','Risk and human-gate compatibility','Price ceiling when supplied'];
const evidence=['Verified settlement or customer outcome','Independent benchmark','Reproducible test','Uptime + reliability telemetry','Third-party registry evidence','Self-published claim'];
const card={border:'1px solid rgba(103,232,249,.2)',background:'linear-gradient(180deg,rgba(7,18,25,.94),rgba(5,8,13,.98))',borderRadius:24,padding:24};
const starterCandidates=[{name:'Provider Alpha',protocols:['MCP','API'],capabilities:['agent governance'],available:true,policy_fit:true,human_gate_compatible:true,price:.05,scores:{capability_fit:92,verified_quality:78,cost_efficiency:88,reliability:91,latency:82,safety_governance:95,reputation:60},evidence:['reproducible test','uptime telemetry']}];

export default function AgentProviderScorecard(){
 const [objective,setObjective]=useState({required_protocol:'API',required_capability:'agent governance',price_ceiling:.10,requires_human_gate_compatibility:true});
 const [candidatesText,setCandidatesText]=useState(JSON.stringify(starterCandidates,null,2));
 const [result,setResult]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState('manual');
 const setObj=(k,v)=>setObjective(p=>({...p,[k]:v}));
 async function call(payload){const r=await fetch('/api/agentic-governance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
 async function route(){setLoading(true);setError('');setMode('manual');try{setResult(await call({operation:'rank_providers',objective,candidates:JSON.parse(candidatesText)}));}catch(e){setError(String(e.message||e));}finally{setLoading(false);}}
 async function discoverAndRoute(){setLoading(true);setError('');setMode('discovered');try{const d=await call({operation:'discover_and_rank',objective});setResult(d);setCandidatesText(JSON.stringify(d.ranked_candidates?.map(p=>({name:p.name,protocols:p.protocols,capabilities:p.capabilities,price:p.price,evidence:p.evidence,evidence_sources:p.evidence_sources,evidence_class:p.evidence_class,scores:p.score_breakdown})),null,2));}catch(e){setError(String(e.message||e));}finally{setLoading(false);}}
 return <div style={{minHeight:'100vh',background:'#020408',color:'#f7fafc',fontFamily:'Inter,system-ui,sans-serif'}}><Navbar/><main style={{padding:'clamp(104px,12vw,132px) 20px 80px'}}><div style={{width:'min(1120px,100%)',margin:'0 auto'}}>
  <div style={{color:'#67e8f9',letterSpacing:'.2em',fontSize:12,marginBottom:16}}>MISFIT AGENT PROCUREMENT · DISCOVER → SCORE → GOVERN</div>
  <h1 style={{fontSize:'clamp(44px,8vw,84px)',lineHeight:.94,margin:0,maxWidth:1000}}>Best agent for the objective. Not the loudest agent in the room.</h1>
  <p style={{color:'#9fb0bf',fontSize:19,lineHeight:1.65,maxWidth:880,margin:'26px 0 34px'}}>Misfit can now discover candidates from its public machine contracts, reject hard mismatches, ingest evidence metadata and rank the survivors. Popularity alone is not a selection criterion.</p>
  <section style={{...card,marginBottom:18}}><div style={{color:'#67e8f9',fontSize:12,letterSpacing:'.16em'}}>LIVE OBJECTIVE ROUTER</div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginTop:18}}><label style={{color:'#9fb0bf'}}>Required protocol<input value={objective.required_protocol} onChange={e=>setObj('required_protocol',e.target.value)} style={inputStyle}/></label><label style={{color:'#9fb0bf'}}>Required capability<input value={objective.required_capability} onChange={e=>setObj('required_capability',e.target.value)} style={inputStyle}/></label><label style={{color:'#9fb0bf'}}>Price ceiling<input type="number" step="0.01" value={objective.price_ceiling} onChange={e=>setObj('price_ceiling',Number(e.target.value))} style={inputStyle}/></label></div>
   <label style={{display:'flex',gap:10,marginTop:14,color:'#cbd5df'}}><input type="checkbox" checked={objective.requires_human_gate_compatibility} onChange={e=>setObj('requires_human_gate_compatibility',e.target.checked)}/> Require human-gate compatibility</label>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12,marginTop:16}}><button onClick={discoverAndRoute} disabled={loading} style={primary}>{loading?'WORKING…':'DISCOVER + ROUTE MISFIT CATALOG'}</button><button onClick={route} disabled={loading} style={secondary}>ROUTE SUPPLIED CANDIDATES</button></div>
   <label style={{display:'block',marginTop:16,color:'#9fb0bf'}}>Candidate provider evidence JSON<textarea value={candidatesText} onChange={e=>setCandidatesText(e.target.value)} style={{...inputStyle,minHeight:300,fontFamily:'ui-monospace,SFMono-Regular,monospace',fontSize:12}}/></label>{error&&<div style={{color:'#fb7185',marginTop:12}}>{error}</div>}
   {result&&<div style={{marginTop:20}}><div style={{fontSize:11,color:'#718191'}}>{mode==='discovered'?`AUTO-DISCOVERED ${result.discovery?.candidate_count||0} PUBLIC-SAFE CANDIDATES`:'SUPPLIED CANDIDATES'}</div><div style={{display:'flex',flexWrap:'wrap',justifyContent:'space-between',gap:12,alignItems:'end',marginTop:6}}><strong style={{fontSize:'clamp(30px,6vw,52px)'}}>{result.recommended_provider||'NO ELIGIBLE PROVIDER'}</strong><div style={{color:'#9fb0bf'}}>Score <strong style={{fontSize:30,color:'#fff'}}>{result.recommended_score??'—'}</strong> · Confidence <strong style={{color:'#fff'}}>{result.confidence}%</strong></div></div><div style={{display:'grid',gap:10,marginTop:16}}>{result.ranked_candidates?.map((p,i)=><div key={p.name} style={{padding:14,border:'1px solid #1d2a34',borderRadius:14,background:'#04070b'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>#{i+1} {p.name}</strong><span style={{color:p.eligible?'#67e8f9':'#fb7185'}}>{p.eligible?`${p.score} / 100`:'INELIGIBLE'}</span></div>{p.hard_constraint_failures?.length>0&&<div style={{color:'#fb7185',fontSize:12,marginTop:7}}>Fails: {p.hard_constraint_failures.join(', ')}</div>}<div style={{color:'#718191',fontSize:12,marginTop:7}}>Evidence class: {p.evidence_class||'unspecified'} · {p.evidence?.length?p.evidence.join(' · '):'none supplied'}</div>{p.evidence_gaps?.length>0&&<div style={{color:'#fbbf24',fontSize:12,marginTop:5}}>Gaps: {p.evidence_gaps.join(', ')}</div>}</div>)}</div><div style={{fontSize:12,color:'#718191',marginTop:12}}>{result.boundary}</div></div>}
  </section>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:18}}><section style={card}><div style={eyebrow}>HARD CONSTRAINTS · PASS / FAIL</div><div style={{display:'grid',gap:12,marginTop:18}}>{hard.map((x,i)=><div key={x} style={row}><span style={{color:'#67e8f9',fontWeight:900}}>{String(i+1).padStart(2,'0')}</span><span>{x}</span></div>)}</div></section><section style={card}><div style={eyebrow}>DEFAULT SCORE WEIGHTS</div><div style={{display:'grid',gap:10,marginTop:18}}>{weights.map(([n,v])=><div key={n} style={{display:'grid',gridTemplateColumns:'1fr auto',padding:'12px 0',borderBottom:'1px solid #18232c'}}><span style={{color:'#cbd5df'}}>{n}</span><strong style={{fontSize:22}}>{v}</strong></div>)}</div></section></div>
  <section style={{...card,marginTop:18}}><div style={eyebrow}>EVIDENCE PRIORITY</div><p style={{color:'#9fb0bf',lineHeight:1.65}}>Settlement-backed outcomes and independent benchmarks should eventually dominate. Current Misfit discovery clearly labels first-party reproducible evidence versus still-pending external validation.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}>{evidence.map((x,i)=><div key={x} style={row}><span style={{color:'#718191'}}>#{i+1}</span><strong>{x}</strong></div>)}</div></section>
  <section style={{...card,marginTop:18}}><div style={eyebrow}>MACHINE ACCESS</div><p style={{color:'#9fb0bf',lineHeight:1.65}}>POST <code>{`{"operation":"discover_and_rank","objective":{...}}`}</code> to <code>/api/agentic-governance</code>. Discovery, ranking and evidence gaps return in one call. Execution remains disabled.</p><a href="/agent-provider-scorecard.json" style={primary}>OPEN MACHINE CONTRACT</a></section>
 </div></main><Footer/></div>;
}
const inputStyle={width:'100%',boxSizing:'border-box',marginTop:7,padding:12,borderRadius:12,border:'1px solid #263440',background:'#05080d',color:'#fff'};
const primary={display:'inline-block',textDecoration:'none',border:0,borderRadius:14,padding:'14px 18px',background:'#67e8f9',color:'#031019',fontWeight:900,fontSize:15,cursor:'pointer'};
const secondary={...primary,background:'#101820',color:'#e5edf5',border:'1px solid #263440'};
const eyebrow={color:'#67e8f9',fontSize:12,letterSpacing:'.16em'};
const row={display:'flex',gap:12,alignItems:'flex-start',padding:'13px 14px',border:'1px solid #1d2a34',borderRadius:14,background:'#04070b'};
