import { useMemo, useState } from 'react';
import { ArrowRight, BrainCircuit, CheckCircle2, ExternalLink, Fingerprint, Gauge, Network, Play, Radar, ShieldCheck } from 'lucide-react';
import Navbar from '../components/Navbar.jsx';
import Footer from '../components/Footer.jsx';

const IDENTITY_RPC='https://cibcxqrqiqvzpardbdrw.supabase.co/rest/v1/rpc/identity_signal_public';
const A2A_GATE='https://cibcxqrqiqvzpardbdrw.supabase.co/functions/v1/misfit-machine-a2a/message:send';
const PUBLIC_KEY='sb_publishable_X-bcgz-3xMIgNZ4rYmAjZA_QNUb69hU';

const governancePresets=[
  {label:'Bounded read',action:'read_status',target:'public_service_health',constraints:{allowed_actions:['read_status'],allowed_targets:['public_service_health']}},
  {label:'External message',action:'send_message',target:'external_slack',constraints:{allowed_targets:['external_slack']}},
  {label:'Out-of-mandate delete',action:'delete_record',target:'production_customer',constraints:{allowed_actions:['read_record'],allowed_targets:['staging_customer']}},
];
const providerObjective={required_protocol:'API',required_capability:'agent governance',price_ceiling:.10,requires_human_gate_compatibility:true};
const identityPresets=[
  ['Evidence first','I need to understand what is actually proven, what is experimental, and what my developers can inspect.'],
  ['Integration mode','I want to understand how this can sit beside an existing MCP and agent workflow stack without replacing the systems that already work.'],
  ['Pilot mode','I am ready to test a bounded pilot. Show me the safest next step, the evidence I should inspect, and what requires human approval.'],
];

async function callProvider(payload){
  const r=await fetch('/api/agentic-governance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
  const d=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(d?.error||`HTTP ${r.status}`);
  return d;
}
async function callActionGate(input){
  const messageId=globalThis.crypto?.randomUUID?.()||`dev-${Date.now()}`;
  const body={message:{messageId,role:'ROLE_USER',parts:[{data:{skill:'governed_agent_action_check',action:input.action,target:input.target,constraints:input.constraints},mediaType:'application/json'}]}};
  const r=await fetch(A2A_GATE,{method:'POST',headers:{'content-type':'application/json','a2a-version':'1.0'},body:JSON.stringify(body)});
  const payload=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(payload?.detail||payload?.title||`HTTP ${r.status}`);
  const parts=Array.isArray(payload?.message?.parts)?payload.message.parts:[];
  const data=parts.map(part=>part?.data).find(value=>value&&typeof value==='object')||{};
  const text=parts.map(part=>part?.text).find(Boolean)||'Governance result returned.';
  return {...data,text,message_id:payload?.message?.messageId||messageId,context_id:payload?.message?.contextId||null,external_action_executed:false};
}
function Status({children,tone='cyan'}){const c=tone==='green'?'border-emerald-300/20 text-emerald-300':tone==='amber'?'border-amber-300/20 text-amber-300':'border-cyan-300/20 text-cyan-300';return <span className={`rounded-full border px-3 py-1.5 font-mono text-[9px] font-bold uppercase tracking-[.12em] ${c}`}>{children}</span>}
function Receipt({label,value}){return <div className="min-w-0 rounded-xl border border-white/8 bg-black/35 p-3"><div className="font-mono text-[8px] uppercase tracking-[.12em] text-slate-600">{label}</div><div className="mt-1 break-words text-sm text-slate-300">{value??'—'}</div></div>}

export default function DeveloperTestDrive(){
 const [action,setAction]=useState(governancePresets[1]);
 const [decision,setDecision]=useState(null),[decisionLoading,setDecisionLoading]=useState(false),[decisionError,setDecisionError]=useState('');
 const [provider,setProvider]=useState(null),[providerLoading,setProviderLoading]=useState(false),[providerError,setProviderError]=useState('');
 const [name,setName]=useState(''),[context,setContext]=useState(identityPresets[0][1]),[identity,setIdentity]=useState(null),[identityLoading,setIdentityLoading]=useState(false),[identityError,setIdentityError]=useState('');
 const completed=useMemo(()=>[decision,provider,identity].filter(Boolean).length,[decision,provider,identity]);
 const allowedActions=(action.constraints?.allowed_actions||[]).join(', '),allowedTargets=(action.constraints?.allowed_targets||[]).join(', ');
 async function runDecision(){setDecisionLoading(true);setDecisionError('');try{setDecision(await callActionGate(action))}catch(e){setDecisionError(String(e?.message||e))}finally{setDecisionLoading(false)}}
 async function runProvider(){setProviderLoading(true);setProviderError('');try{setProvider(await callProvider({operation:'discover_probe_rank',objective:providerObjective,include_external:true}))}catch(e){setProviderError(String(e?.message||e))}finally{setProviderLoading(false)}}
 async function runIdentity(){if(!name.trim()||!context.trim()){setIdentityError('Enter a name and current context.');return}setIdentityLoading(true);setIdentityError('');try{const r=await fetch(IDENTITY_RPC,{method:'POST',headers:{'Content-Type':'application/json',apikey:PUBLIC_KEY},body:JSON.stringify({p_name:name.trim(),p_context:context.trim()})});const d=await r.json();if(!r.ok)throw new Error(d?.message||d?.error||'Identity Signal unavailable.');setIdentity(d)}catch(e){setIdentityError(String(e?.message||e))}finally{setIdentityLoading(false)}}
 const identityProfile=identity?.identity_signal,comparison=identity?.comparison;
 return <div className="min-h-screen bg-black text-white"><Navbar/><main className="mx-auto max-w-7xl px-4 pb-24 pt-24 sm:px-5 md:pt-28">
  <section className="overflow-hidden rounded-[2rem] border border-cyan-300/20 bg-[radial-gradient(circle_at_10%_10%,rgba(34,211,238,.13),transparent_28%),radial-gradient(circle_at_90%_10%,rgba(217,70,239,.12),transparent_30%),linear-gradient(135deg,#061018,#020305_58%,#08020b)] p-5 md:p-9">
   <div className="flex flex-wrap items-center justify-between gap-3"><div className="font-mono text-[10px] uppercase tracking-[.18em] text-cyan-300">MISFIT DEVELOPER TEST DRIVE · V2</div><div className="flex flex-wrap gap-2"><Status>LIVE PROOF</Status><Status tone="green">PUBLIC-SAFE</Status><Status tone="amber">NO EXTERNAL ACTION EXECUTED</Status></div></div>
   <div className="mt-7 grid gap-7 lg:grid-cols-[1.08fr_.92fr] lg:items-end"><div><h1 className="font-display text-4xl font-bold leading-[.95] sm:text-5xl md:text-7xl">DON'T READ THE PITCH. <span className="text-cyan-300">DRIVE THE SYSTEM.</span></h1><p className="mt-5 max-w-3xl text-[15px] leading-7 text-slate-300">Three bounded live tests: govern an action through the published A2A boundary, discover and verify agent providers, then see how the same facts can be presented differently to a specific human without changing authority or safety policy.</p></div><div className="rounded-3xl border border-white/10 bg-black/45 p-5"><div className="flex items-center justify-between gap-3"><span className="font-mono text-[9px] uppercase tracking-[.13em] text-slate-500">Test progress</span><strong className="text-2xl">{completed}/3</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-cyan-300 transition-all" style={{width:`${completed/3*100}%`}}/></div><p className="mt-3 text-xs leading-5 text-slate-500">Public surfaces return decisions, evidence and receipts. They do not expose private GHOSBC reconstruction material or execute payments, messages, account mutations or target-agent skills.</p></div></div>
  </section>

  <section className="mt-5 rounded-3xl border border-cyan-300/20 bg-cyan-300/[.025] p-5 md:p-7">
   <div className="flex items-start gap-3"><ShieldCheck className="mt-1 shrink-0 text-cyan-300"/><div className="min-w-0"><div className="font-mono text-[9px] uppercase tracking-[.15em] text-cyan-300">01 · CONSEQUENCE GATE</div><h2 className="mt-1 text-2xl font-semibold md:text-3xl">Does this action fit the declared authority envelope?</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">This calls Misfit Machine Agent's published <span className="font-mono text-cyan-200">governed_agent_action_check</span> skill directly. The action is evaluated and returned as ALLOW / REVIEW / BLOCK. The proposed external action is never executed by this test.</p></div></div>
   <div className="mt-5 flex flex-wrap gap-2">{governancePresets.map(p=><button key={p.label} onClick={()=>{setAction(p);setDecision(null)}} className="min-h-11 rounded-full border border-white/10 px-4 font-mono text-[9px] uppercase tracking-[.1em] text-slate-400 hover:border-cyan-300/30 hover:text-cyan-200">{p.label}</button>)}</div>
   <div className="mt-4 grid min-w-0 gap-4 lg:grid-cols-[1fr_.9fr]">
    <div className="min-w-0 rounded-2xl border border-white/10 bg-black/40 p-4">
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Action<input value={action.action} onChange={e=>{setDecision(null);setAction(p=>({...p,action:e.target.value}))}} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black px-3 font-mono text-xs text-white"/></label><label className="text-xs text-slate-500">Target<input value={action.target} onChange={e=>{setDecision(null);setAction(p=>({...p,target:e.target.value}))}} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black px-3 font-mono text-xs text-white"/></label></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Allowed actions<input value={allowedActions} onChange={e=>{setDecision(null);setAction(p=>({...p,constraints:{...p.constraints,allowed_actions:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}}))}} placeholder="read_status" className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black px-3 font-mono text-xs text-white"/></label><label className="text-xs text-slate-500">Allowed targets<input value={allowedTargets} onChange={e=>{setDecision(null);setAction(p=>({...p,constraints:{...p.constraints,allowed_targets:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}}))}} placeholder="public_service_health" className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black px-3 font-mono text-xs text-white"/></label></div>
      <button onClick={runDecision} disabled={decisionLoading} className="mt-4 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-cyan-300 px-4 font-mono text-[10px] font-bold uppercase tracking-[.12em] text-black disabled:opacity-50"><Play size={14}/>{decisionLoading?'Checking boundary…':'Run live A2A gate'}</button>{decisionError&&<div className="mt-3 rounded-xl border border-rose-300/20 bg-rose-300/[.06] p-3 text-sm text-rose-200">{decisionError}</div>}
    </div>
    <div className="min-w-0 rounded-2xl border border-white/10 bg-black/40 p-4">{!decision?<p className="text-sm leading-6 text-slate-600">Decision receipt appears here.</p>:<><div className="flex flex-wrap items-center justify-between gap-3"><strong className="text-4xl uppercase">{decision.decision||'UNKNOWN'}</strong><Status tone={decision.decision==='ALLOW'?'green':decision.decision==='REVIEW'?'amber':'cyan'}>{decision.requires_human_review?'HUMAN REVIEW':'NO HUMAN REVIEW'}</Status></div><p className="mt-3 text-sm leading-6 text-slate-400">{decision.text}</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Receipt label="Normalized action" value={`${decision.normalized_action?.action||action.action} → ${decision.normalized_action?.target||action.target}`}/><Receipt label="External execution" value="false"/><Receipt label="Allowed" value={String(Boolean(decision.allowed))}/><Receipt label="Message receipt" value={decision.message_id}/></div><div className="mt-3 rounded-xl border border-white/8 p-3"><div className="font-mono text-[8px] uppercase tracking-[.12em] text-slate-600">Public reason codes</div><div className="mt-2 break-words text-sm text-slate-300">{decision.reasons?.join(' · ')||'No public reason codes returned'}</div></div></>}</div>
   </div>
  </section>

  <section className="mt-5 rounded-3xl border border-fuchsia-300/20 bg-fuchsia-300/[.02] p-5 md:p-7">
   <div className="flex items-start gap-3"><Network className="mt-1 shrink-0 text-fuchsia-300"/><div className="min-w-0"><div className="font-mono text-[9px] uppercase tracking-[.15em] text-fuchsia-300">02 · PROVIDER ROUTER</div><h2 className="mt-1 text-2xl font-semibold md:text-3xl">Discover → probe → rank.</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">The router discovers public machine contracts, runs bounded metadata/health/latency/contract probes and ranks eligible providers against the same objective. It does not invoke target skills.</p></div></div>
   <div className="mt-5 grid gap-4 lg:grid-cols-[.75fr_1.25fr]"><div className="min-w-0 rounded-2xl border border-white/10 bg-black/40 p-4"><div className="grid gap-2"><Receipt label="Protocol" value={providerObjective.required_protocol}/><Receipt label="Capability" value={providerObjective.required_capability}/><Receipt label="Price ceiling" value={`$${providerObjective.price_ceiling}`}/><Receipt label="Human gate" value="required"/></div><button onClick={runProvider} disabled={providerLoading} className="mt-4 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-fuchsia-300 px-4 font-mono text-[10px] font-bold uppercase tracking-[.12em] text-black disabled:opacity-50"><Radar size={14}/>{providerLoading?'Probing…':'Discover + live verify'}</button>{providerError&&<div className="mt-3 rounded-xl border border-rose-300/20 bg-rose-300/[.06] p-3 text-sm text-rose-200">{providerError}</div>}</div>
    <div className="min-w-0 rounded-2xl border border-white/10 bg-black/40 p-4">{!provider?<p className="text-sm leading-6 text-slate-600">Provider recommendation and evidence appear here.</p>:<><div className="font-mono text-[9px] uppercase tracking-[.12em] text-slate-600">Recommended provider</div><div className="mt-2 break-words text-3xl font-semibold">{provider.recommended_provider||'No eligible provider'}</div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Receipt label="Score" value={provider.recommended_score}/><Receipt label="Confidence" value={`${provider.confidence??'—'}%`}/><Receipt label="Live-probed" value={provider.active_evidence?.probed_candidates??0}/></div><div className="mt-3 space-y-2">{provider.ranked_candidates?.slice(0,3).map((p,i)=><div key={`${p.source_registry}-${p.name}-${i}`} className="min-w-0 rounded-xl border border-white/8 p-3"><div className="flex min-w-0 items-center justify-between gap-3"><strong className="min-w-0 break-words text-sm">#{i+1} {p.name}</strong><span className="shrink-0 font-mono text-[9px] text-fuchsia-300">{p.eligible?`${p.score}/100`:'INELIGIBLE'}</span></div>{p.probe_summary&&<div className="mt-2 break-words text-[11px] leading-5 text-slate-600">Probe: {p.probe_status} · {p.probe_summary.success_rate}% success · avg {p.probe_summary.avg_latency_ms??'—'} ms</div>}</div>)}</div></>}</div>
   </div>
  </section>

  <section className="mt-5 rounded-3xl border border-emerald-300/20 bg-emerald-300/[.02] p-5 md:p-7">
   <div className="flex items-start gap-3"><Fingerprint className="mt-1 shrink-0 text-emerald-300"/><div className="min-w-0"><div className="font-mono text-[9px] uppercase tracking-[.15em] text-emerald-300">03 · IDENTITY SIGNAL</div><h2 className="mt-1 text-2xl font-semibold md:text-3xl">Same facts. Different human interface.</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">Name anchors the session; current context drives public-safe adaptation. This demonstrates response pacing, structure and escalation changes without silently changing authority.</p></div></div>
   <div className="mt-5 grid gap-4 lg:grid-cols-[.85fr_1.15fr]"><div className="min-w-0 rounded-2xl border border-white/10 bg-black/40 p-4"><label className="block text-xs text-slate-500">Identity anchor<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} placeholder="Stan Hansen" className="mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-black px-3 text-white"/></label><label className="mt-3 block text-xs text-slate-500">Current context<textarea value={context} onChange={e=>setContext(e.target.value)} maxLength={800} className="mt-2 min-h-28 w-full rounded-xl border border-white/10 bg-black p-3 text-sm text-white"/></label><div className="mt-3 flex flex-wrap gap-2">{identityPresets.map(([l,v])=><button key={l} type="button" onClick={()=>setContext(v)} className="min-h-10 rounded-full border border-white/10 px-3 font-mono text-[8px] uppercase tracking-[.1em] text-slate-500">{l}</button>)}</div><button onClick={runIdentity} disabled={identityLoading} className="mt-4 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-300 px-4 font-mono text-[10px] font-bold uppercase tracking-[.12em] text-black disabled:opacity-50"><BrainCircuit size={14}/>{identityLoading?'Decoding…':'Run personalization proof'}</button>{identityError&&<div className="mt-3 rounded-xl border border-rose-300/20 bg-rose-300/[.06] p-3 text-sm text-rose-200">{identityError}</div>}</div>
    <div className="min-w-0 rounded-2xl border border-white/10 bg-black/40 p-4">{!identityProfile||!comparison?<p className="text-sm leading-6 text-slate-600">Personalization receipt and A/B comparison appear here.</p>:<><div className="grid gap-2 sm:grid-cols-2"><Receipt label="State marker" value={identityProfile.state_marker}/><Receipt label="Routing lane" value={identityProfile.routing_lane}/><Receipt label="Pace" value={identityProfile.pace}/><Receipt label="Detail depth" value={identityProfile.detail_depth}/></div><div className="mt-3 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-white/8 p-3"><div className="font-mono text-[8px] uppercase tracking-[.12em] text-slate-600">Generic agent</div><p className="mt-2 text-sm leading-6 text-slate-400">{comparison.generic_agent}</p></div><div className="rounded-xl border border-emerald-300/20 bg-emerald-300/[.03] p-3"><div className="font-mono text-[8px] uppercase tracking-[.12em] text-emerald-300">Identity/context aware</div><p className="mt-2 text-sm leading-6 text-slate-200">{comparison.identity_context_aware_agent}</p></div></div></>}</div>
   </div>
  </section>

  <section className="mt-5 overflow-hidden rounded-3xl border border-white/10 bg-[linear-gradient(135deg,rgba(34,211,238,.055),rgba(217,70,239,.045),rgba(0,0,0,.95))] p-5 md:p-7"><div className="flex items-center gap-3"><Gauge className="text-cyan-300"/><div><div className="font-mono text-[9px] uppercase tracking-[.14em] text-cyan-300">GO DEEPER</div><h2 className="mt-1 text-2xl font-semibold">Inspect the contracts and full benches.</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Governed Agent Fleet','/agentic-governed-fleet','Full consequence controls'],['Provider Scorecard','/agent-provider-scorecard','Full discovery + evidence'],['Agent Evaluation Lab','/agent-evaluation-lab','Contracts + AE100'],['Frontier Map','/frontier','Maturity + research boundaries']].map(([n,u,d])=><a key={n} href={u} className="min-w-0 rounded-2xl border border-white/10 bg-black/35 p-4 transition hover:border-cyan-300/25"><div className="flex items-center justify-between gap-3"><strong className="break-words">{n}</strong><ExternalLink size={14} className="shrink-0 text-slate-600"/></div><p className="mt-2 text-xs leading-5 text-slate-600">{d}</p></a>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-emerald-300/15 bg-emerald-300/[.025] p-4"><div className="flex min-w-0 items-start gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-300" size={16}/><p className="min-w-0 text-xs leading-6 text-slate-500">The test drive proves bounded public behavior. It is not a certification and it does not expose the private cognitive kernel, private policy mappings, credentials or reconstruction material.</p></div><a href="/operator?challenge=developer-test-drive&track=partner" className="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-cyan-300 px-4 font-mono text-[9px] font-bold uppercase tracking-[.1em] text-black">Run a pilot <ArrowRight size={13}/></a></div></section>
 </main><Footer/></div>
}
