import { useEffect, useMemo, useState } from 'react';
import { Clapperboard, Gamepad2, Globe2, Radio, Server, ShieldCheck, Sparkles, Users, Wrench } from 'lucide-react';
import Navbar from '../components/Navbar.jsx';
import Footer from '../components/Footer.jsx';
import GTAGrowthOS from '../components/GTAGrowthOS.jsx';

const SB='https://cibcxqrqiqvzpardbdrw.supabase.co';
const PK='sb_publishable_X-bcgz-3xMIgNZ4rYmAjZA_QNUb69hU';
const H={apikey:PK,'Content-Type':'application/json'};
const official={cfx:'https://cfx.re/',tebex:'https://www.tebex.io/server',gta6:'https://www.rockstargames.com/VI'};

async function rest(path,opts={}){
  const r=await fetch(`${SB}/rest/v1/${path}`,{...opts,headers:{...H,...(opts.headers||{})}});
  const text=await r.text();
  const data=text?JSON.parse(text):null;
  if(!r.ok)throw new Error(data?.message||data?.hint||`Request failed (${r.status})`);
  return data;
}
async function catalog(body){
  const r=await fetch(`${SB}/functions/v1/public-catalog`,{method:'POST',headers:H,body:JSON.stringify(body)});
  const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={}}
  if(!r.ok)throw new Error(data?.error||`Request failed (${r.status})`);
  return data;
}

export default function GTAHub(){
  const [servers,setServers]=useState([]),[creators,setCreators]=useState([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
  const [tab,setTab]=useState('servers');
  const [serverForm,setServerForm]=useState({name:'',region:'',category:'Roleplay',website_url:'',discord_url:'',connect_url:'',email:'',description:''});
  const [creatorForm,setCreatorForm]=useState({display_name:'',primary_platform:'YouTube',channel_url:'',email:'',bio:''});
  const [serviceForm,setServiceForm]=useState({name:'',email:'',message:'',request_type:'server_service'});
  const [busy,setBusy]=useState('');

  const load=async()=>{setLoading(true);try{const [s,c]=await Promise.all([
    rest('gaming_servers?select=id,name,platform,category,region,connect_url,website_url,discord_url,description,tags,updated_at&status=eq.approved&order=updated_at.desc'),
    rest('gaming_creators?select=id,display_name,channel_url,primary_platform,specialties,bio,updated_at&status=eq.approved&order=updated_at.desc')
  ]);setServers(s||[]);setCreators(c||[])}catch(e){setNotice(`Registry: ${e.message}`)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const stats=useMemo(()=>[{label:'APPROVED SERVERS',value:servers.length},{label:'CREATORS',value:creators.length},{label:'CURRENT RAIL',value:'GTA V / FiveM'},{label:'GTA VI',value:'WATCHLIST'}],[servers,creators]);

  const submitServer=async(e)=>{e.preventDefault();setBusy('server');setNotice('');try{await catalog({operation:'submit_gta_server',name:serverForm.name.trim(),category:serverForm.category||null,region:serverForm.region||null,connect_url:serverForm.connect_url||null,website_url:serverForm.website_url||null,discord_url:serverForm.discord_url||null,description:serverForm.description||null,email:serverForm.email||null});setNotice('Server submitted. It stays private until Misfit approves it.');setServerForm({name:'',region:'',category:'Roleplay',website_url:'',discord_url:'',connect_url:'',email:'',description:''})}catch(e){setNotice(`Server submission: ${e.message}`)}finally{setBusy('')}};
  const submitCreator=async(e)=>{e.preventDefault();setBusy('creator');setNotice('');try{await catalog({operation:'submit_gta_creator',display_name:creatorForm.display_name.trim(),primary_platform:creatorForm.primary_platform||null,channel_url:creatorForm.channel_url||null,email:creatorForm.email||null,bio:creatorForm.bio||null});setNotice('Creator profile submitted for review.');setCreatorForm({display_name:'',primary_platform:'YouTube',channel_url:'',email:'',bio:''})}catch(e){setNotice(`Creator submission: ${e.message}`)}finally{setBusy('')}};
  const submitService=async(e)=>{e.preventDefault();setBusy('service');setNotice('');try{await catalog({operation:'submit_gta_request',request_type:serviceForm.request_type,name:serviceForm.name.trim(),email:serviceForm.email||null,message:serviceForm.message,source:'gta_hub'});setNotice('Request received by Misfit Cloud.');setServiceForm({name:'',email:'',message:'',request_type:'server_service'})}catch(e){setNotice(`Request: ${e.message}`)}finally{setBusy('')}};

  return <div className="min-h-screen bg-black text-white"><Navbar/><main className="mx-auto max-w-7xl px-4 pb-24 pt-24 sm:px-5 md:pt-28">
    <section className="overflow-hidden rounded-[1.8rem] border border-fuchsia-400/20 bg-[radial-gradient(circle_at_15%_0%,rgba(217,70,239,.22),transparent_34%),radial-gradient(circle_at_90%_20%,rgba(34,211,238,.16),transparent_30%),linear-gradient(145deg,#0b0710,#020307_62%,#000)] p-5 md:p-10">
      <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-fuchsia-300/25 bg-fuchsia-300/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.18em] text-fuchsia-200"><Gamepad2 size={14}/> MISFIT GTA CREATOR NETWORK · BETA</div><h1 className="mt-5 max-w-5xl font-display text-[2.7rem] font-black leading-[.94] sm:text-6xl md:text-7xl">OWN THE <span className="text-fuchsia-300">AUDIENCE</span>. BUILD THE <span className="text-cyan-300">ECONOMY</span>.</h1><p className="mt-5 max-w-3xl text-[15px] leading-7 text-slate-300">A Misfit-operated discovery and creator layer around permitted GTA community-server activity: find servers, surface creators, request infrastructure, and build clip/content workflows without cheats, credential abuse, ban evasion, prohibited gambling, or fake GTA VI support.</p></div><div className="shrink-0 rounded-2xl border border-amber-300/25 bg-amber-300/[.06] p-4 md:max-w-xs"><div className="font-mono text-[10px] text-amber-300">GTA VI WATCH</div><div className="mt-2 text-xl font-bold">November 19, 2026</div><p className="mt-2 text-xs leading-5 text-slate-500">Official Rockstar release date. This portal does not assume FiveM/Cfx support transfers to GTA VI.</p><a href={official.gta6} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-10 items-center text-xs font-bold text-amber-200">ROCKSTAR SOURCE →</a></div></div>
      <div className="mt-7 grid grid-cols-2 gap-2 lg:grid-cols-4">{stats.map(x=><div key={x.label} className="min-w-0 rounded-2xl border border-white/10 bg-black/35 p-3"><div className="font-mono text-[9px] text-slate-600">{x.label}</div><div className="mt-1 break-words text-lg font-bold">{x.value}</div></div>)}</div>
    </section>

    {notice&&<button onClick={()=>setNotice('')} className="mt-4 w-full rounded-2xl border border-cyan-300/20 bg-cyan-300/[.05] p-4 text-left text-sm text-cyan-100">{notice}<span className="float-right">×</span></button>}

    <GTAGrowthOS/>

    <section className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      <Rail icon={Server} title="SERVER DISCOVERY" copy="Approved community servers with category, region and join links. Misfit does not operate or endorse a server merely because it is listed."/>
      <Rail icon={Users} title="CREATOR NETWORK" copy="Streamers, clip makers, hosts and community creators surfaced as a separate commerce and audience layer."/>
      <Rail icon={Clapperboard} title="CLIPS + CONTENT" copy="Request short-form clipping, creator workflows, publishing systems and analytics around permitted creator content."/>
      <Rail icon={Wrench} title="SERVER SERVICES" copy="Request compliant infrastructure, onboarding, analytics and community operations—not cheats or prohibited automation."/>
    </section>

    <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.025] p-4 md:p-6"><div className="grid grid-cols-3 gap-2"><Tab active={tab==='servers'} onClick={()=>setTab('servers')}>SERVERS</Tab><Tab active={tab==='creators'} onClick={()=>setTab('creators')}>CREATORS</Tab><Tab active={tab==='build'} onClick={()=>setTab('build')}>BUILD WITH MISFIT</Tab></div>
      {tab==='servers'&&<div className="mt-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-cyan-300">COMMUNITY SERVER REGISTRY</div><h2 className="mt-1 text-2xl font-bold">Find a place worth playing.</h2></div><a href={official.cfx} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center rounded-xl border border-cyan-300/20 px-4 font-mono text-[10px] text-cyan-200">OPEN CFX →</a></div><div className="mt-4 grid gap-3 md:grid-cols-2">{loading?<Empty text="Loading approved servers…"/>:servers.length?servers.map(s=><ServerCard key={s.id} s={s}/>):<Empty text="Registry is live. No server has passed Misfit review yet—submit one below."/>}</div><ServerForm form={serverForm} setForm={setServerForm} submit={submitServer} busy={busy==='server'}/></div>}
      {tab==='creators'&&<div className="mt-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-fuchsia-300">CREATOR DISCOVERY</div><h2 className="mt-1 text-2xl font-bold">Creators are the distribution layer.</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{loading?<Empty text="Loading approved creators…"/>:creators.length?creators.map(c=><CreatorCard key={c.id} c={c}/>):<Empty text="No creator has passed review yet. Be the first profile in the network."/>}</div><CreatorForm form={creatorForm} setForm={setCreatorForm} submit={submitCreator} busy={busy==='creator'}/></div>}
      {tab==='build'&&<div className="mt-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-emerald-300">MISFIT SERVICE LANE</div><h2 className="mt-1 text-2xl font-bold">Build around the community, not around cheating.</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><Mini title="SERVER OPS" copy="Onboarding, infrastructure planning, analytics and community systems."/><Mini title="CONTENT PIPELINE" copy="Clips, creator workflows, publishing, affiliate/referral mechanics where permitted."/><Mini title="PARTNERSHIPS" copy="Creators, communities and permitted services routed through a reviewable Misfit relationship."/></div><ServiceForm form={serviceForm} setForm={setServiceForm} submit={submitService} busy={busy==='service'}/></div>}
    </section>

    <section className="mt-5 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-emerald-300/20 bg-emerald-300/[.035] p-5"><div className="flex items-center gap-2 text-emerald-300"><ShieldCheck size={18}/><h2 className="text-xl font-bold">Compliance is part of the product.</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{['No game cheats or ban evasion','No credential sharing or theft','No prohibited botting','No real-money gambling mechanics','No sale of Rockstar-created virtual items','No fake “official brand server” claims','No assumption of GTA VI / FiveM parity','Every public listing requires review'].map(x=><div key={x} className="rounded-xl border border-white/8 bg-black/35 p-3 text-xs text-slate-400">✓ {x}</div>)}</div></div><div className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-slate-500">ECOSYSTEM LINKS</div><a href={official.cfx} target="_blank" rel="noreferrer" className="mt-4 flex min-h-12 items-center justify-between rounded-xl border border-white/10 px-4 text-sm"><span>Cfx / FiveM</span><Globe2 size={15}/></a><a href={official.tebex} target="_blank" rel="noreferrer" className="mt-2 flex min-h-12 items-center justify-between rounded-xl border border-white/10 px-4 text-sm"><span>Tebex server commerce</span><Sparkles size={15}/></a><a href="/creator-commerce" className="mt-2 flex min-h-12 items-center justify-between rounded-xl border border-fuchsia-300/20 bg-fuchsia-300/[.05] px-4 text-sm text-fuchsia-200"><span>Misfit Creator Commerce</span><Radio size={15}/></a></div></section>

    <section className="mt-5 rounded-2xl border border-white/10 bg-black/60 p-4 text-xs leading-6 text-slate-600">Misfit GTA Creator Network is an independent Misfit Mediahouse product and is not affiliated with or endorsed by Rockstar Games, Take-Two Interactive, Cfx.re, or Tebex. Third-party names are used only to describe ecosystem compatibility and source context.</section>
  </main><Footer/></div>
}

function Rail({icon:Icon,title,copy}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><Icon size={18} className="text-cyan-300"/><div className="mt-3 font-mono text-[10px] font-bold text-white">{title}</div><p className="mt-2 text-xs leading-5 text-slate-500">{copy}</p></div>}
function Tab({active,onClick,children}){return <button onClick={onClick} className={`min-h-12 rounded-xl border px-2 font-mono text-[9px] font-bold sm:text-[10px] ${active?'border-cyan-300 bg-cyan-300 text-black':'border-white/10 bg-black/40 text-slate-500'}`}>{children}</button>}
function Empty({text}){return <div className="rounded-2xl border border-dashed border-white/10 bg-black/30 p-6 text-sm text-slate-600 md:col-span-2">{text}</div>}
function ServerCard({s}){return <div className="min-w-0 rounded-2xl border border-white/10 bg-black/40 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-bold">{s.name}</h3><div className="mt-1 font-mono text-[9px] text-cyan-300">{[s.category,s.region,s.platform].filter(Boolean).join(' · ').toUpperCase()}</div></div><span className="rounded-full bg-emerald-300/10 px-2 py-1 font-mono text-[8px] text-emerald-300">APPROVED</span></div><p className="mt-3 text-xs leading-5 text-slate-500">{s.description||'Community server listing.'}</p><div className="mt-4 flex flex-wrap gap-2">{s.connect_url&&<a href={s.connect_url} target="_blank" rel="noreferrer" className="rounded-lg bg-cyan-300 px-3 py-2 font-mono text-[9px] font-bold text-black">CONNECT</a>}{s.website_url&&<a href={s.website_url} target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 px-3 py-2 font-mono text-[9px]">WEBSITE</a>}{s.discord_url&&<a href={s.discord_url} target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 px-3 py-2 font-mono text-[9px]">DISCORD</a>}</div></div>}
function CreatorCard({c}){return <div className="rounded-2xl border border-white/10 bg-black/40 p-4"><div className="font-mono text-[9px] text-fuchsia-300">{c.primary_platform?.toUpperCase()||'CREATOR'}</div><h3 className="mt-1 text-lg font-bold">{c.display_name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{c.bio||'Misfit creator network profile.'}</p>{c.channel_url&&<a href={c.channel_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-10 items-center font-mono text-[9px] text-cyan-300">OPEN CHANNEL →</a>}</div>}
function Field(props){return <input {...props} className="min-h-12 min-w-0 rounded-xl border border-white/10 bg-black px-3 text-sm outline-none focus:border-cyan-300/50"/>}
function Area(props){return <textarea {...props} className="min-h-28 w-full rounded-xl border border-white/10 bg-black p-3 text-sm outline-none focus:border-cyan-300/50"/>}
function ServerForm({form,setForm,submit,busy}){return <form onSubmit={submit} className="mt-6 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.025] p-4"><div className="font-mono text-[10px] text-cyan-300">SUBMIT A SERVER</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Field required placeholder="Server name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field placeholder="Region" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/><Field placeholder="Website URL" type="url" value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})}/><Field placeholder="Discord URL" type="url" value={form.discord_url} onChange={e=>setForm({...form,discord_url:e.target.value})}/><Field placeholder="https://cfx.re/join/..." type="url" value={form.connect_url} onChange={e=>setForm({...form,connect_url:e.target.value})}/><Field placeholder="Contact email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><Area className="mt-2" placeholder="What kind of server is it? What makes it worth listing?" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><p className="mt-2 text-[11px] leading-5 text-slate-600">Submitting attests this request does not depend on cheats, prohibited gambling, credential abuse, ban evasion, or unauthorized automation. Listings remain private until approved.</p><button disabled={busy} className="mt-3 min-h-12 rounded-xl bg-cyan-300 px-4 font-mono text-[10px] font-bold text-black disabled:opacity-50">{busy?'SUBMITTING…':'SUBMIT FOR REVIEW'}</button></form>}
function CreatorForm({form,setForm,submit,busy}){return <form onSubmit={submit} className="mt-6 rounded-2xl border border-fuchsia-300/15 bg-fuchsia-300/[.025] p-4"><div className="font-mono text-[10px] text-fuchsia-300">JOIN AS A CREATOR</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Field required placeholder="Creator / channel name" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><select value={form.primary_platform} onChange={e=>setForm({...form,primary_platform:e.target.value})} className="min-h-12 rounded-xl border border-white/10 bg-black px-3 text-sm"><option>YouTube</option><option>Twitch</option><option>TikTok</option><option>Kick</option><option>Instagram</option><option>Other</option></select><Field placeholder="Channel URL" type="url" value={form.channel_url} onChange={e=>setForm({...form,channel_url:e.target.value})}/><Field placeholder="Contact email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><Area className="mt-2" placeholder="Tell Misfit what you make: streams, clips, hosting, roleplay, cars, builds, commentary…" value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/><button disabled={busy} className="mt-3 min-h-12 rounded-xl bg-fuchsia-300 px-4 font-mono text-[10px] font-bold text-black disabled:opacity-50">{busy?'SUBMITTING…':'JOIN CREATOR NETWORK'}</button></form>}
function ServiceForm({form,setForm,submit,busy}){return <form onSubmit={submit} className="mt-6 rounded-2xl border border-emerald-300/15 bg-emerald-300/[.025] p-4"><div className="grid gap-2 sm:grid-cols-2"><Field required placeholder="Your name / community" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><select value={form.request_type} onChange={e=>setForm({...form,request_type:e.target.value})} className="min-h-12 rounded-xl border border-white/10 bg-black px-3 text-sm sm:col-span-2"><option value="server_service">Server / community services</option><option value="clip_workflow">Clips + content workflow</option><option value="partnership">Creator / community partnership</option></select></div><Area className="mt-2" required placeholder="What do you want Misfit to build or operate?" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><p className="mt-2 text-[11px] leading-5 text-slate-600">This lane accepts compliant creator/community infrastructure requests only. No cheats, credential abuse, ban evasion, prohibited gambling or unauthorized automation.</p><button disabled={busy} className="mt-3 min-h-12 rounded-xl bg-emerald-300 px-4 font-mono text-[10px] font-bold text-black disabled:opacity-50">{busy?'SENDING…':'SEND TO MISFIT CLOUD'}</button></form>}
function Mini({title,copy}){return <div className="rounded-xl border border-white/10 bg-black/35 p-4"><div className="font-mono text-[9px] text-emerald-300">{title}</div><p className="mt-2 text-xs leading-5 text-slate-500">{copy}</p></div>}
