import { useEffect, useState } from 'react';
import heroDesktop from '../assets/tyler/tyler-mountain-lodge-hero.webp';
import crateHero from '../assets/tyler/tyler-crate-hero.webp';

const PHONE = '+18017910165';
const LEAD_ENDPOINT = 'https://cibcxqrqiqvzpardbdrw.supabase.co/functions/v1/tyler-contractor-lead';
const CRATE_CHECKOUT = 'https://buy.stripe.com/28E5kD0saeCWfd05Ne8ww0s';

const services = [
  ['⌂', 'General construction', 'Repairs, build-outs, punch-list work and practical improvements from scope through finish.', true],
  ['▰', 'Remodels & renovations', 'Interior updates, demo, rebuild and finish work that makes an existing home work better.', true],
  ['▥', 'Flooring & finish work', 'Flooring, trim, doors and finish details built for everyday use and clean mountain-home style.', true],
  ['⌁', 'Outdoor builds & hardscape', 'Patios, walls, steps and outdoor spaces that fit the terrain and the property.', false],
  ['◒', 'Landscape & property work', 'Landscape installs, cleanup and outdoor improvements shaped around the home and site.', false],
  ['❄', 'Snow removal & seasonal care', 'Winter access, snow removal and year-round property support for Eden-area homes.', false],
];

export default function TylerWard() {
  const [kind, setKind] = useState('bid_request');
  const [status, setStatus] = useState('');

  useEffect(() => {
    const oldTitle = document.title;
    const description = document.querySelector('meta[name="description"]');
    const canonical = document.querySelector('link[rel="canonical"]');
    const oldDescription = description?.getAttribute('content');
    const oldCanonical = canonical?.getAttribute('href');
    document.title = 'Tyler Ward | General Contractor · Eden, Utah';
    description?.setAttribute('content', 'Tyler Ward provides general construction, remodeling, flooring, outdoor builds, landscaping, snow removal and property work in Eden and Ogden Valley, Utah.');
    canonical?.setAttribute('href', 'https://misfitmediahouse.com/tyler-ward');
    return () => {
      document.title = oldTitle;
      if (description && oldDescription) description.setAttribute('content', oldDescription);
      if (canonical && oldCanonical) canonical.setAttribute('href', oldCanonical);
    };
  }, []);

  async function submitLead(e) {
    e.preventDefault();
    const form = e.currentTarget;
    const raw = Object.fromEntries(new FormData(form).entries());
    const contact = String(raw.contact || '').trim();
    delete raw.contact;
    raw.kind = kind;
    raw.email = contact.includes('@') ? contact : '';
    raw.phone = contact.includes('@') ? '' : contact;
    raw.contact_preference = contact.includes('@') ? 'email' : 'text';
    raw.time_window = 'flexible';
    if (!raw.phone && !raw.email) { setStatus('Add a phone number or email so Tyler can follow up.'); return; }
    setStatus('Sending…');
    try {
      const r = await fetch(LEAD_ENDPOINT, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(raw) });
      const j = await r.json();
      if (!r.ok || !j.ok) throw new Error('save failed');
      setStatus(kind === 'site_visit' ? 'Site-visit request saved — Tyler can confirm directly.' : 'Request saved — Tyler has your project details.');
      form.reset(); setKind('bid_request');
    } catch { setStatus('Could not save that request yet. Call or text Tyler and we’ll get it handled.'); }
  }

  return (
    <div className="tw">
      <style>{`
        .tw{--black:#0b0d0a;--deep:#11150f;--forest:#1d281c;--moss:#687b5d;--paper:#f2eadb;--paper2:#f8f3e9;--sand:#dcc79a;--ink:#151713;--rust:#aa4d2a;--white:#f8f4ea;background:var(--paper);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.35;min-height:100vh}
        .tw *{box-sizing:border-box}.tw a{color:inherit}.tw .wrap{width:min(1180px,calc(100% - 36px));margin:auto}
        .tw .top{background:var(--black);color:var(--white);border-bottom:1px solid rgba(255,255,255,.08);position:relative;z-index:20}.tw .topbar{height:92px;display:flex;align-items:center;justify-content:space-between;gap:18px}.tw .brand{font-size:clamp(28px,4vw,45px);font-weight:950;line-height:.9;letter-spacing:-.045em}.tw .brand small{display:block;font-size:11px;line-height:1.25;letter-spacing:.13em;color:#91a175;text-transform:uppercase;margin-top:10px}.tw .topactions{display:flex;gap:12px}.tw .iconBtn{height:54px;width:54px;border:1px solid rgba(220,199,154,.28);border-radius:13px;display:grid;place-items:center;text-decoration:none;background:#111510;color:#f4efdf;font-size:24px}.tw .hamb{font-size:0}.tw .hamb:before{content:"☰";font-size:29px}
        .tw .hero{position:relative;overflow:hidden;background:#0c0f0c;color:white;min-height:610px}.tw .heroMedia{position:absolute;inset:0}.tw .heroMedia img{width:100%;height:100%;display:block;object-fit:cover;object-position:72% center}.tw .heroShade{position:absolute;inset:0;background:linear-gradient(90deg,rgba(7,9,7,.92) 0%,rgba(7,9,7,.82) 28%,rgba(7,9,7,.38) 54%,rgba(7,9,7,.06) 100%)}.tw .heroInner{position:relative;z-index:2;min-height:610px;display:flex;align-items:center;padding:50px 0 58px}.tw .heroCopy{width:min(620px,61%)}.tw .eyebrow,.tw .kicker{font-size:12px;font-weight:900;letter-spacing:.16em;text-transform:uppercase}.tw .eyebrow{color:#a2b487;margin-bottom:16px}.tw h1{margin:0;color:#f7f2e8;font-size:clamp(64px,9vw,112px);line-height:.72;letter-spacing:-.075em}.tw h1 span{display:block;color:var(--sand)}.tw .lede{font-size:20px;max-width:570px;margin:27px 0 25px;color:#e5e2d9}.tw .actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;max-width:520px}.tw .btn{border:0;text-decoration:none;border-radius:8px;min-height:54px;padding:0 18px;display:flex;align-items:center;justify-content:space-between;font-weight:950;font-size:14px;text-transform:uppercase;letter-spacing:.02em;cursor:pointer}.tw .bid{background:#f1e7cf;color:#161913}.tw .visit{background:#6f835f;color:white}.tw .call{background:#171c15;color:#f5f1e8;border:1px solid rgba(255,255,255,.13)}.tw .text{background:#ac4d28;color:white}.tw .arr{font-size:25px;font-weight:500}
        .tw .tradeStrip{background:#d6c28e;color:#151713;border-top:1px solid rgba(0,0,0,.28);border-bottom:1px solid rgba(0,0,0,.18)}.tw .tradeStrip .wrap{padding:11px 0;display:flex;gap:20px;overflow:hidden;white-space:nowrap;font-size:11px;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.tw .tradeStrip span:before{content:"■";font-size:7px;color:var(--rust);margin-right:9px;vertical-align:2px}.tw .section{padding:42px 0}.tw .services{background:var(--paper2)}.tw .sectionHead{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:22px}.tw .kicker{color:#647653}.tw .sectionHead h2,.tw .product h2,.tw .contact h2{font-size:clamp(44px,6vw,72px);line-height:.84;letter-spacing:-.055em;margin:6px 0 0}.tw .outlineBtn{border:1px solid #7f7767;border-radius:999px;padding:11px 18px;text-decoration:none;font-size:12px;font-weight:900;text-transform:uppercase;white-space:nowrap}.tw .cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.tw .serviceCard{background:#121710;color:#f0ede3;border-radius:13px;padding:20px;min-height:205px;box-shadow:0 15px 35px rgba(17,24,16,.12);border-top:3px solid #71835f}.tw .serviceCard.construction{border-top-color:var(--rust)}.tw .serviceIcon{font-size:33px;color:#879b69;line-height:1;margin-bottom:24px}.tw .construction .serviceIcon{color:#c06a45}.tw .serviceCard b{display:block;font-size:13px;letter-spacing:.13em;text-transform:uppercase;margin-bottom:9px}.tw .serviceCard p{margin:0;color:#d0cec5;font-size:15px}.tw .serviceFoot{margin-top:18px;padding-top:16px;border-top:1px solid rgba(21,23,19,.13);display:flex;flex-wrap:wrap;gap:8px}.tw .serviceFoot span{font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;border:1px solid #a99e89;border-radius:999px;padding:7px 9px;color:#4f554a}
        .tw .product{background:#0f140e;color:#f6f1e6;padding:42px 0}.tw .productShell{border:1px solid rgba(255,255,255,.08);border-radius:15px;overflow:hidden;display:grid;grid-template-columns:.88fr 1.12fr;min-height:400px;background:#151a13}.tw .productCopy{padding:30px 28px}.tw .product .kicker{color:#b95b35}.tw .product h2{font-size:clamp(44px,5vw,67px);margin-bottom:16px}.tw .productIntro{font-size:19px;max-width:520px;color:#e5e1d7;margin:0 0 18px}.tw .features{display:grid;gap:8px;font-size:15px}.tw .features div:before{content:"✓";display:inline-grid;place-items:center;width:20px;height:20px;border:1px solid #7e9164;border-radius:50%;margin-right:9px;color:#93a773;font-size:12px}.tw .chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}.tw .chip{border:1px solid rgba(255,255,255,.35);border-radius:999px;padding:7px 10px;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.11em}.tw .productVisual{position:relative;min-height:400px;background-position:center;background-size:cover;background-repeat:no-repeat}.tw .productVisual:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(21,26,19,.88),rgba(21,26,19,.06) 25%)}.tw .buyBox{position:absolute;right:20px;bottom:20px;display:flex;overflow:hidden;border-radius:10px;background:#f4efe4;color:#192017;text-decoration:none;box-shadow:0 18px 50px rgba(0,0,0,.32);z-index:2}.tw .buyCopy{padding:11px 16px 10px}.tw .buyCopy b{display:block;font-size:12px;text-transform:uppercase}.tw .priceRow{display:flex;align-items:end;gap:12px}.tw .price{font-size:31px;font-weight:950;line-height:1}.tw .pickup{font-size:10px;font-weight:900;line-height:1.1;text-transform:uppercase}.tw .buyArrow{width:66px;background:#70815d;display:grid;place-items:center;font-size:35px}
        .tw .contact{background:#f0e8d8;padding:38px 0 40px}.tw .contactGrid{display:grid;grid-template-columns:.75fr 1.25fr;gap:46px;align-items:start}.tw .contact .kicker{color:#2d3828}.tw .benefits{display:grid;gap:10px;margin-top:27px;font-size:14px}.tw .benefits div:before{content:"✓";display:inline-grid;place-items:center;width:23px;height:23px;border:1px solid #80916b;border-radius:50%;margin-right:9px;color:#627b51}.tw .form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tw .form input,.tw .form select,.tw .form textarea{width:100%;border:1px solid #a99e89;background:#f5efe3;border-radius:5px;padding:14px 13px;font:inherit;color:#191c18;outline:none}.tw .form textarea{grid-column:1/-1;min-height:100px;resize:vertical}.tw .form button{grid-column:1/-1;background:#637b52;color:white;border:0;border-radius:5px;padding:15px;font-weight:950;text-transform:uppercase;letter-spacing:.08em;cursor:pointer}.tw .formStatus{grid-column:1/-1;font-size:13px;font-weight:800;min-height:18px}.tw .honeypot{position:absolute;left:-10000px;opacity:0}.tw footer{background:#171c15;color:#d0cec4;padding:21px 0}.tw .footer{display:flex;align-items:center;justify-content:space-between;gap:20px}.tw .footerBrand{font-size:24px;font-weight:950;letter-spacing:-.04em}.tw .footerBrand small{display:block;color:#889b6f;font-size:9px;text-transform:uppercase;letter-spacing:.1em}.tw .built{display:inline-flex;align-items:center;gap:9px;font-size:13px;font-weight:900;text-decoration:none;border-bottom:1px solid rgba(220,199,154,.35);padding-bottom:3px}.tw .built span{color:#dcc79a}.tw .sticky{display:none}
        @media(max-width:880px){.tw .wrap{width:min(100% - 28px,760px)}.tw .topbar{height:76px}.tw .brand{font-size:31px}.tw .iconBtn{height:48px;width:48px}.tw .heroInner{min-height:620px}.tw .heroCopy{width:72%}.tw h1{font-size:82px}.tw .cards{grid-template-columns:1fr 1fr}.tw .productShell{grid-template-columns:1fr}.tw .productVisual{min-height:380px}.tw .contactGrid{grid-template-columns:1fr}.tw .footer{align-items:flex-end}}
        @media(max-width:600px){.tw .wrap{width:calc(100% - 24px)}.tw .topbar{height:78px}.tw .brand{font-size:29px}.tw .brand small{font-size:8.5px;margin-top:7px;letter-spacing:.1em}.tw .iconBtn{width:46px;height:46px}.tw .topactions{gap:8px}.tw .hero{min-height:720px}.tw .heroMedia img{object-position:88% center;transform:scale(1.04)}.tw .heroShade{background:linear-gradient(180deg,rgba(8,10,8,.02) 0%,rgba(8,10,8,.08) 34%,rgba(8,10,8,.72) 61%,rgba(8,10,8,.98) 82%)}.tw .heroInner{min-height:720px;align-items:flex-end;padding:320px 0 28px}.tw .heroCopy{width:100%}.tw .eyebrow{font-size:9.5px;margin-bottom:10px}.tw h1{font-size:62px;line-height:.79}.tw .lede{font-size:17px;margin:18px 0;max-width:100%}.tw .actions{grid-template-columns:1fr 1fr}.tw .btn{min-height:50px;font-size:12px;padding:0 13px}.tw .tradeStrip .wrap{overflow:auto;scrollbar-width:none}.tw .tradeStrip .wrap::-webkit-scrollbar{display:none}.tw .section{padding:32px 0}.tw .sectionHead{align-items:flex-start}.tw .sectionHead h2{font-size:48px}.tw .outlineBtn{display:none}.tw .cards{grid-template-columns:1fr 1fr;gap:10px}.tw .serviceCard{min-height:198px;padding:16px}.tw .serviceIcon{margin-bottom:19px}.tw .serviceCard p{font-size:13px}.tw .serviceFoot{gap:6px}.tw .serviceFoot span{font-size:9px;padding:6px 8px}.tw .product{padding:22px 0}.tw .productShell{display:block}.tw .productCopy{padding:24px 19px}.tw .product h2{font-size:45px}.tw .productIntro{font-size:16px}.tw .features{font-size:13px}.tw .productVisual{min-height:330px}.tw .buyBox{right:12px;bottom:12px}.tw .buyCopy{padding:9px 12px}.tw .price{font-size:26px}.tw .buyArrow{width:54px}.tw .contact{padding:30px 0 92px}.tw .contact h2{font-size:47px}.tw .contactGrid{gap:25px}.tw .form{grid-template-columns:1fr}.tw .form textarea,.tw .form button,.tw .formStatus{grid-column:1}.tw footer{padding:20px 0 84px}.tw .built{font-size:11px}.tw .footerBrand{font-size:20px}.tw .footer{align-items:flex-end}.tw .sticky{position:fixed;display:grid;grid-template-columns:1fr 1fr;gap:10px;left:10px;right:10px;bottom:10px;z-index:80;background:rgba(15,19,14,.94);padding:9px;border-radius:18px;backdrop-filter:blur(12px)}.tw .sticky a{text-decoration:none;text-align:center;padding:14px 10px;border-radius:11px;color:white;font-weight:950}.tw .sticky a:first-child{background:#6b7f60}.tw .sticky a:last-child{background:#aa4d2a}}
      `}</style>

      <header className="top"><div className="wrap topbar"><div className="brand">TYLER WARD<small>General Contracting · Construction · Property & Landscape</small></div><div className="topactions"><a className="iconBtn" href={`tel:${PHONE}`} aria-label="Call Tyler">☎</a><a className="iconBtn hamb" href="#services" aria-label="View services">Menu</a></div></div></header>
      <section className="hero"><div className="heroMedia" aria-hidden="true"><img src={heroDesktop} alt="" /><div className="heroShade" /></div><div className="wrap heroInner"><div className="heroCopy"><div className="eyebrow">Eden · Ogden Valley · Mountain homes</div><h1>Build it.<br /><span>Make it last.</span></h1><p className="lede">General construction, remodels, flooring, repairs, outdoor builds, landscaping and year-round property work for homes in Eden and the surrounding valley.</p><div className="actions"><a className="btn bid" href="#contact" onClick={() => setKind('bid_request')}>Request a bid <span className="arr">→</span></a><a className="btn visit" href="#contact" onClick={() => setKind('site_visit')}>Book a site visit <span className="arr">▣</span></a><a className="btn call" href={`tel:${PHONE}`}>Call Tyler <span className="arr">⌕</span></a><a className="btn text" href={`sms:${PHONE}?body=Hey%20Tyler%2C%20I%20found%20your%20site%20and%20want%20to%20talk%20about%20a%20project.`}>Text Tyler <span className="arr">◌</span></a></div></div></div></section>
      <div className="tradeStrip" aria-label="Services at a glance"><div className="wrap"><span>General Construction</span><span>Remodels</span><span>Flooring</span><span>Repairs</span><span>Outdoor Builds</span><span>Landscaping</span><span>Snow Removal</span></div></div>
      <section className="section services" id="services"><div className="wrap"><div className="sectionHead"><div><div className="kicker">Mountain homes · inside + out</div><h2>One call.<br />Whole property.</h2></div><a className="outlineBtn" href="#contact">Request a bid →</a></div><div className="cards">{services.map(([icon, title, copy, construction]) => (<article className={`serviceCard${construction ? ' construction' : ''}`} key={title}><div className="serviceIcon">{icon}</div><b>{title}</b><p>{copy}</p></article>))}</div><div className="serviceFoot"><span>Construction</span><span>Remodeling</span><span>Flooring</span><span>Repairs</span><span>Hardscape</span><span>Landscaping</span><span>Snow Removal</span><span>Maintenance</span></div></div></section>
      <section className="product" id="shop"><div className="wrap productShell"><div className="productCopy"><div className="kicker">Limited. Authentic. One of a kind.</div><h2>Make Love,<br />Not War.</h2><p className="productIntro">Genuine WWII .50 caliber ammunition crates, repurposed and planted with soil and seasonal flowers.</p><div className="features"><div>Real WWII .50 caliber ammunition crates</div><div>Planted with premium soil & seasonal flowers</div><div>Limited supply — each one is unique</div><div>Local pickup in Eden, Utah</div></div><div className="chips"><span className="chip">Limited supply</span><span className="chip">WWII .50 cal crates</span><span className="chip">Pickup in Eden</span></div></div><div className="productVisual" style={{ backgroundImage: `url(${crateHero})` }}><a className="buyBox" href={CRATE_CHECKOUT} target="_blank" rel="noopener noreferrer" aria-label="Reserve a planted crate for $495"><div className="buyCopy"><b>Reserve a crate</b><div className="priceRow"><span className="price">$495</span><span className="pickup">Local pickup<br />in Eden, Utah</span></div></div><span className="buyArrow">→</span></a></div></div></section>
      <section className="contact" id="contact"><div className="wrap contactGrid"><div><div className="kicker">Construction, landscape or property work?</div><h2>Let’s get your<br />project moving.</h2><div className="benefits"><div>Inside + outside projects</div><div>Fast, local response</div><div>Straight answers</div></div></div><form className="form" onSubmit={submitLead}><input type="hidden" name="project_key" value="tyler-ward-contractor-site" /><div className="honeypot"><input name="website" tabIndex="-1" autoComplete="off" /></div><input name="name" placeholder="Your Name" required /><input name="contact" placeholder="Phone or Email" required /><select name="service" defaultValue=""><option value="">Project Type</option><option value="general_construction">General construction</option><option value="remodel">Remodel / renovation</option><option value="flooring">Flooring / finish work</option><option value="repairs">Repairs / punch list</option><option value="outdoor_builds">Outdoor builds / hardscape</option><option value="landscaping">Landscaping</option><option value="snow_removal">Snow removal</option><option value="property_maintenance">Property maintenance</option><option value="other">Other</option></select><input name="preferred_date" type="datetime-local" aria-label="Preferred day and time" /><textarea name="message" placeholder="Tell us about your project..." /><button type="submit">Send request →</button><div className="formStatus">{status}</div></form></div></section>
      <footer><div className="wrap footer"><div className="footerBrand">TYLER WARD<small>General Contracting · Construction · Property & Landscape</small></div><a className="built" href="/" aria-label="Visit Misfit Mediahouse">Built by <span>misfit MEdiAHouse</span> →</a></div></footer>
      <div className="sticky"><a href={`tel:${PHONE}`}>Call Tyler</a><a href={`sms:${PHONE}?body=Hey%20Tyler%2C%20I%20want%20to%20talk%20about%20a%20project.`}>Text Tyler</a></div>
    </div>
  );
}
