import { useEffect, useMemo, useState } from 'react';
import { Activity, BrainCircuit, Gauge, History, LockKeyhole, Radar, RefreshCw, ShieldCheck, Trophy, WalletCards } from 'lucide-react';
import Navbar from '../components/Navbar.jsx';
import Footer from '../components/Footer.jsx';

const FEED='https://cibcxqrqiqvzpardbdrw.supabase.co/functions/v1/noop-probe';
const STORAGE='misfit-signal-paper-v3';
const starting={cash:100000,positions:{},trades:[],startingEquity:100000};
const money=(n)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Number(n)<10?4:2}).format(Number(n||0));
const pct=(n)=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const tone=(n)=>Number(n)>=0?'text-emerald-300':'text-red-300';

export default function WorldForge(){
 const [feed,setFeed]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const [paper,setPaper]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||starting}catch{return starting}});
 const [ticket,setTicket]=useState({symbol:'BTC',usd:1000});
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(FEED,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j?.error||'feed unavailable');setFeed(j)}catch(e){setError(e.message||'feed unavailable')}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]); useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify(paper)),[paper]);
 const assets=feed?.assets||[], emotion=feed?.emotion, auto=feed?.paper_autopilot?.accounts||[], sports=feed?.prediction_markets?.sports||[], preds=feed?.prediction_markets?.markets||[];
 const prices=useMemo(()=>Object.fromEntries(assets.map(a=>[a.symbol,Number(a.price_usd||0)])),[assets]);
 const posVal=useMemo(()=>Object.entries(paper.positions||{}).reduce((s,[sym,p])=>s+Number(p.qty||0)*Number(prices[sym]||p.last||0),0),[paper,prices]);
 const equity=Number(paper.cash||0)+posVal, pnl=equity-Number(paper.startingEquity||100000), exposure=equity?posVal/equity*100:0;
 const stance=useMemo(()=>{const s=Number(emotion?.score??50);if(s<=28)return['CAPITULATION WATCH','Extreme fear. Test mean reversion against further downside.'];if(s<42)return['DEFENSIVE','Guarded regime. Smaller sizing and more confirmation.'];if(s<58)return['MIXED / WAIT','No strong emotional edge. Let more evidence resolve the conflict.'];if(s<72)return['RISK-ON WATCH','Improving crowd regime. Test continuation without assuming certainty.'];return['EUPHORIA RISK','Greed is elevated. Momentum and reversal risk both matter.']},[emotion]);
 const trade=(side)=>{const sym=ticket.symbol,px=Number(prices[sym]||0),usd=Math.max(1,Number(ticket.usd||0));if(!px)return setNotice('No live price.');setPaper(prev=>{const p=prev.positions[sym]||{qty:0,cost:0,last:px};let cash=Number(prev.cash),qty=Number(p.qty),cost=Number(p.cost),fill=usd;if(side==='buy'){if(usd>cash){setNotice('Paper order rejected: not enough virtual cash.');return prev}qty+=usd/px;cost+=usd;cash-=usd}else{const q=Math.min(usd/px,qty);if(q<=0){setNotice('Paper order rejected: no position to sell.');return prev}fill=q*px;const avg=qty?cost/qty:0;qty-=q;cost=Math.max(0,cost-q*avg);cash+=fill}const positions={...prev.positions,[sym]:{qty,cost,last:px}};if(qty<1e-12)delete positions[sym];setNotice(`PAPER ${side.toUpperCase()} ${sym} ${money(fill)} @ ${money(px)}`);return{...prev,cash,positions,trades:[{id:Date.now(),side,symbol:sym,usd:fill,price:px,emotion:emotion?.label,regime:emotion?.regime,at:new Date().toISOString()},...(prev.trades||[])].slice(0,40)}})};
 return <div className="min-h-screen bg-black text-white"><Navbar/><main className="mx-auto max-w-7xl px-4 pb-24 pt-24 sm:px-5 md:pt-28">
  <section className="rounded-[1.6rem] border border-cyan-400/20 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,.16),transparent_35%),radial-gradient(circle_at_bottom_right,rgba(168,85,247,.15),transparent_36%),linear-gradient(135deg,#071018,#000)] p-5 md:p-10">
   <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="inline-flex w-fit items-center gap-2 rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.18em] text-cyan-300"><Radar size={13}/> MISFIT SIGNAL · EMOTIONAL TRADING INTELLIGENCE</div><div className="flex gap-2"><span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1.5 font-mono text-[10px] text-emerald-300">AUTO PAPER LIVE</span><span className="rounded-full border border-amber-400/25 bg-amber-400/10 px-3 py-1.5 font-mono text-[10px] text-amber-300">REAL MONEY GATED</span></div></div>
   <h1 className="mt-6 max-w-5xl font-display text-[2.55rem] font-bold leading-[.98] sm:text-5xl md:text-7xl">TRADE THE <span className="text-cyan-300">HUMAN FIELD</span>, NOT JUST THE CANDLE.</h1>
   <p className="mt-5 max-w-4xl text-[15px] leading-7 text-slate-300">Misfit Signal combines live market emotion, autonomous virtual portfolios and prediction-market intelligence. The point is proof: every strategy decision, bankroll and outcome is measurable before real capital gets authority.</p>
   <div className="mt-6 flex flex-wrap gap-3"><button onClick={load} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-cyan-300 px-4 py-3 font-mono text-xs font-bold text-black"><RefreshCw size={14} className={loading?'animate-spin':''}/>REFRESH SIGNAL</button><a href="/command" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-4 py-3 font-mono text-xs text-slate-300">FOUNDER COMMAND</a></div>
  </section>
  {error&&<div className="mt-4 rounded-2xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}{notice&&<button onClick={()=>setNotice('')} className="mt-4 w-full rounded-2xl border border-cyan-400/20 bg-cyan-400/[.06] p-4 text-left text-sm text-cyan-100">{notice}<span className="float-right">×</span></button>}
  <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={BrainCircuit} label="FIELD EMOTION" value={loading?'…':emotion?.label?.toUpperCase()||'—'} sub={emotion?`${emotion.score}/100 composite`:'waiting'}/><Metric icon={Activity} label="REGIME" value={emotion?.regime?.replaceAll('_',' ').toUpperCase()||'—'} sub={emotion?`Fear/Greed ${emotion.fear_greed}`:'—'}/><Metric icon={Gauge} label="MANUAL EXPOSURE" value={`${exposure.toFixed(1)}%`} sub={`${money(posVal)} deployed`}/><Metric icon={WalletCards} label="MANUAL EQUITY" value={money(equity)} sub={`${pnl>=0?'+':''}${money(pnl)} P/L`} valueClass={tone(pnl)}/></section>
  <section className="mt-5 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-cyan-300">LIVE MARKET FIELD</div><h2 className="mt-1 text-2xl font-semibold">Market tape</h2><div className="mt-4 space-y-2">{assets.map(a=><div key={a.symbol} className="grid grid-cols-[1fr_auto_auto] gap-3 rounded-xl border border-white/8 bg-black/40 p-3"><div><b>{a.name}</b> <span className="font-mono text-xs text-cyan-300">{a.symbol}</span></div><div>{money(a.price_usd)}</div><div className={tone(a.change_24h_pct)}>{pct(a.change_24h_pct)}</div></div>)}</div></div><div className="rounded-3xl border border-cyan-400/20 bg-cyan-400/[.035] p-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-cyan-300">SIGNAL INTERPRETATION</div><h2 className="mt-3 text-2xl font-bold">{stance[0]}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{stance[1]}</p><div className="mt-4 grid grid-cols-2 gap-3"><Mini label="Breadth" value={emotion?`${Math.round(emotion.market_breadth*100)}%`:'—'}/><Mini label="Avg 24h" value={emotion?pct(emotion.avg_24h_change_pct):'—'}/><Mini label="Fear/Greed" value={emotion?.fear_greed??'—'}/><Mini label="Volatility" value={emotion?Number(emotion.avg_abs_24h_change_pct).toFixed(2):'—'}/></div></div></section>
  <section className="mt-5 rounded-3xl border border-violet-400/20 bg-violet-400/[.035] p-5 md:p-7"><div className="flex items-center gap-2 text-violet-300"><Trophy size={17}/><div className="font-mono text-[10px] uppercase tracking-[.16em]">AUTONOMOUS PAPER LEADERBOARD · 15-MIN CYCLES</div></div><h2 className="mt-2 text-2xl font-semibold">Same signal. Different bankrolls.</h2><p className="mt-2 text-sm text-slate-400">Server-side strategy engine now runs $100, $1,000, $2,500 and $10,000 virtual portfolios automatically. Results persist in Misfit Cloud and cannot move real money.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{auto.map(a=><div key={a.account_key} className="rounded-2xl border border-white/10 bg-black/40 p-4"><div className="font-mono text-[10px] text-slate-500">START {money(a.starting_cash)}</div><div className="mt-2 text-2xl font-bold">{money(a.equity)}</div><div className={`mt-1 text-sm ${tone(a.pnl)}`}>{pct(a.return_pct)} · {money(a.pnl)}</div><div className="mt-3 text-xs text-slate-500">{a.trade_count} trades · cash {money(a.cash)}</div></div>)}</div></section>
  <section className="mt-5 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl border border-emerald-400/20 bg-emerald-400/[.035] p-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-emerald-300">MANUAL PAPER LAB</div><h2 className="mt-2 text-2xl font-semibold">Order ticket</h2><div className="mt-4 grid grid-cols-2 gap-3"><select value={ticket.symbol} onChange={e=>setTicket({...ticket,symbol:e.target.value})} className="min-h-12 rounded-xl border border-white/10 bg-black px-3">{assets.map(a=><option key={a.symbol}>{a.symbol}</option>)}</select><input type="number" value={ticket.usd} onChange={e=>setTicket({...ticket,usd:e.target.value})} className="min-h-12 rounded-xl border border-white/10 bg-black px-3"/></div><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>trade('buy')} className="min-h-14 rounded-xl bg-emerald-300 font-bold text-black">PAPER BUY</button><button onClick={()=>trade('sell')} className="min-h-14 rounded-xl border border-red-400/30 bg-red-400/10 font-bold text-red-200">PAPER SELL</button></div></div><div className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center gap-2"><History size={16} className="text-cyan-300"/><h2 className="text-xl font-semibold">Manual paper portfolio</h2></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Cash" value={money(paper.cash)}/><Mini label="Positions" value={money(posVal)}/><Mini label="P/L" value={money(pnl)}/></div><div className="mt-4 space-y-2">{Object.entries(paper.positions||{}).length?Object.entries(paper.positions).map(([sym,p])=><div key={sym} className="rounded-xl border border-white/8 bg-black/40 p-3 text-sm"><b>{sym}</b> · {Number(p.qty).toFixed(6)} · {money(Number(p.qty)*(prices[sym]||p.last))}</div>):<div className="text-sm text-slate-600">No manual paper positions yet.</div>}</div></div></section>
  <section className="mt-5 grid gap-4 lg:grid-cols-2"><Prediction title="SPORTS / FIGHTS OVERLAY" items={sports} empty="No sports markets returned in this refresh."/><Prediction title="KALSHI PREDICTION-MARKET OVERLAY" items={preds} empty="No prediction markets returned in this refresh."/></section>
  <section className="mt-5 rounded-3xl border border-amber-400/20 bg-amber-400/[.035] p-5"><div className="flex items-center gap-2 text-amber-300"><LockKeyhole size={18}/><h2 className="text-xl font-semibold">Real-money execution</h2></div><p className="mt-3 text-sm leading-6 text-slate-400">Still intentionally disabled. Production brokerage or prediction-market trading will only graduate after paper evidence, explicit owner approval, max position size, daily loss limit, leverage policy, kill switch and audit rules exist. Current autonomous strategies cannot place real orders or bets.</p></section>
  <section className="mt-5 rounded-3xl border border-cyan-400/15 bg-cyan-400/[.025] p-5"><div className="flex items-center gap-2 text-cyan-300"><ShieldCheck size={18}/><h2 className="text-xl font-semibold">Proof before pitch</h2></div><p className="mt-3 text-sm leading-7 text-slate-500">The free-trial sales story should be the live evidence: how the signal behaved, how autonomous portfolios performed, where it failed, drawdown, hit rate and whether it beat simple benchmarks. No fake edge, no guaranteed-return language, and no protected GHOSBC/Soul Cipher internals exposed.</p></section>
 </main><Footer/></div>
}
function Metric({icon:Icon,label,value,sub,valueClass=''}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500"><Icon size={14}/>{label}</div><div className={`mt-3 text-xl font-bold ${valueClass}`}>{value}</div><div className="mt-1 text-xs text-slate-600">{sub}</div></div>}
function Mini({label,value}){return <div className="rounded-xl border border-white/8 bg-black/40 p-3"><div className="font-mono text-[9px] uppercase text-slate-600">{label}</div><div className="mt-1 text-sm font-semibold">{value}</div></div>}
function Prediction({title,items,empty}){return <div className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-cyan-300">{title}</div><div className="mt-4 space-y-2">{items.length?items.slice(0,10).map(m=><div key={m.ticker} className="rounded-xl border border-white/8 bg-black/40 p-3"><div className="text-sm font-semibold leading-5">{m.title}</div><div className="mt-2 flex items-center justify-between text-xs text-slate-500"><span>{m.ticker}</span><span className="text-cyan-300">YES {m.yes_probability_pct}%</span></div></div>):<div className="text-sm text-slate-600">{empty}</div>}</div></div>}
