import { useEffect, useMemo, useState } from 'react';
import { Activity, BrainCircuit, Gauge, History, LockKeyhole, Radar, RefreshCw, ShieldCheck, Trophy, WalletCards } from 'lucide-react';
import Navbar from '../components/Navbar.jsx';
import Footer from '../components/Footer.jsx';

const FEED='https://cibcxqrqiqvzpardbdrw.supabase.co/functions/v1/noop-probe';
const COMMERCE='https://cibcxqrqiqvzpardbdrw.supabase.co/functions/v1/public-catalog';
const STORAGE='misfit-signal-paper-v3';
const ACCESS_STORAGE='misfit-trader-founding-session-v1';
const TRADER_PRODUCT='misfit_trader_founding_access_10';
const starting={cash:100000,positions:{},trades:[],startingEquity:100000};
const money=(n)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Number(n)<10?4:2}).format(Number(n||0));
const pct=(n)=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const tone=(n)=>Number(n)>=0?'text-emerald-300':'text-red-300';
const chartDays=[1,7,14,30];

export default function WorldForge(){
 const [feed,setFeed]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const [paper,setPaper]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||starting}catch{return starting}});
 const [ticket,setTicket]=useState({symbol:'BTC',usd:1000});
 const [chartAsset,setChartAsset]=useState('bitcoin'),[days,setDays]=useState(7),[chart,setChart]=useState(null),[chartError,setChartError]=useState(''),[chartLoading,setChartLoading]=useState(true);
 const [access,setAccess]=useState(null),[checkoutLoading,setCheckoutLoading]=useState(false);
 const [capitalMode,setCapitalMode]=useState('paper'),[controlMode,setControlMode]=useState('manual');

 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(FEED,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j?.error||'feed unavailable');setFeed(j)}catch(e){setError(e.message||'feed unavailable')}finally{setLoading(false)}};
 const loadChart=async()=>{setChartLoading(true);setChartError('');try{const r=await fetch(`${FEED}?chart=${encodeURIComponent(chartAsset)}&days=${days}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j?.detail||j?.error||'chart unavailable');setChart(j)}catch(e){setChart(null);setChartError(e.message||'chart unavailable')}finally{setChartLoading(false)}};
 const verifyAccess=async(sessionId,attempt=0)=>{try{const r=await fetch(`${COMMERCE}?op=entitlement&session_id=${encodeURIComponent(sessionId)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j?.message||j?.error||'entitlement verification failed');setAccess(j);if(j.status==='active'){setNotice(`FOUNDING SUPPORTER VERIFIED${j.email_hint?` · ${j.email_hint}`:''}`);try{history.replaceState({},'',location.pathname)}catch{}}else if(j.status==='pending'&&attempt<8){setNotice('Payment received. Waiting for signed Stripe entitlement evidence…');setTimeout(()=>verifyAccess(sessionId,attempt+1),1200)}}catch(e){setNotice(`Access verification: ${e.message||e}`)}};
 const buyAccess=async()=>{setCheckoutLoading(true);setNotice('');try{const r=await fetch(COMMERCE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'create_checkout',product_key:TRADER_PRODUCT})});const j=await r.json();if(!r.ok||!j.checkout_url)throw new Error(j?.message||j?.error||'checkout unavailable');location.assign(j.checkout_url)}catch(e){setNotice(`Checkout: ${e.message||e}`);setCheckoutLoading(false)}};
 const selectMode=(capital,control)=>{setCapitalMode(capital);setControlMode(control);if(capital==='live')setNotice(control==='manual'?'LIVE MANUAL selected. Broker account onboarding, KYC and funding must be connected before any real order can be submitted.':'LIVE MISFIT AI selected. Broker onboarding plus explicit bounded trading authority and risk rails must pass before autonomous real-money execution can activate.');};

 useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
 useEffect(()=>{loadChart()},[chartAsset,days]);
 useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify(paper)),[paper]);
 useEffect(()=>{try{const q=new URLSearchParams(location.search),returned=q.get('session_id'),stored=localStorage.getItem(ACCESS_STORAGE),session=returned||stored;if(returned?.startsWith('cs_'))localStorage.setItem(ACCESS_STORAGE,returned);if(session?.startsWith('cs_'))verifyAccess(session);if(q.get('purchase')==='success'&&!session)setNotice('Payment returned without a checkout receipt. Contact Misfit if this persists.')}catch{}},[]);

 const assets=feed?.assets||[], emotion=feed?.emotion, auto=feed?.paper_autopilot?.accounts||[], sports=feed?.prediction_markets?.sports||[], preds=feed?.prediction_markets?.markets||[];
 const prices=useMemo(()=>Object.fromEntries(assets.map(a=>[a.symbol,Number(a.price_usd||0)])),[assets]);
 const posVal=useMemo(()=>Object.entries(paper.positions||{}).reduce((s,[sym,p])=>s+Number(p.qty||0)*Number(prices[sym]||p.last||0),0),[paper,prices]);
 const equity=Number(paper.cash||0)+posVal, pnl=equity-Number(paper.startingEquity||100000), exposure=equity?posVal/equity*100:0;
 const stance=useMemo(()=>{const s=Number(emotion?.score??50);if(s<=28)return['CAPITULATION WATCH','Extreme fear. Test mean reversion against further downside.'];if(s<42)return['DEFENSIVE','Guarded regime. Smaller sizing and more confirmation.'];if(s<58)return['MIXED / WAIT','No strong emotional edge. Let more evidence resolve the conflict.'];if(s<72)return['RISK-ON WATCH','Improving crowd regime. Test continuation without assuming certainty.'];return['EUPHORIA RISK','Greed is elevated. Momentum and reversal risk both matter.']},[emotion]);
 const trade=(side)=>{const sym=ticket.symbol,px=Number(prices[sym]||0),usd=Math.max(1,Number(ticket.usd||0));if(!px)return setNotice('No live price.');setPaper(prev=>{const p=prev.positions[sym]||{qty:0,cost:0,last:px};let cash=Number(prev.cash),qty=Number(p.qty),cost=Number(p.cost),fill=usd;if(side==='buy'){if(usd>cash){setNotice('Paper order rejected: not enough virtual cash.');return prev}qty+=usd/px;cost+=usd;cash-=usd}else{const q=Math.min(usd/px,qty);if(q<=0){setNotice('Paper order rejected: no position to sell.');return prev}fill=q*px;const avg=qty?cost/qty:0;qty-=q;cost=Math.max(0,cost-q*avg);cash+=fill}const positions={...prev.positions,[sym]:{qty,cost,last:px}};if(qty<1e-12)delete positions[sym];setNotice(`PAPER ${side.toUpperCase()} ${sym} ${money(fill)} @ ${money(px)}`);return{...prev,cash,positions,trades:[{id:Date.now(),side,symbol:sym,usd:fill,price:px,emotion:emotion?.label,regime:emotion?.regime,at:new Date().toISOString()},...(prev.trades||[])].slice(0,40)}})};

 return <div className="min-h-screen bg-black text-white"><Navbar/><main className="mx-auto max-w-7xl px-4 pb-24 pt-24 sm:px-5 md:pt-28">
  <section className="rounded-[1.6rem] border border-cyan-400/20 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,.16),transparent_35%),radial-gradient(circle_at_bottom_right,rgba(168,85,247,.15),transparent_36%),linear-gradient(135deg,#071018,#000)] p-5 md:p-10">
   <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="inline-flex w-fit items-center gap-2 rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.18em] text-cyan-300"><Radar size={13}/> MISFIT TRADER · SIGNAL + CANDLE INTELLIGENCE</div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-cyan-400/25 bg-cyan-400/10 px-3 py-1.5 font-mono text-[10px] text-cyan-300">FREE TRADER LIVE</span><span className="rounded-full border border-fuchsia-400/25 bg-fuchsia-400/10 px-3 py-1.5 font-mono text-[10px] text-fuchsia-300">FOUNDING SUPPORTER · $10</span><span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1.5 font-mono text-[10px] text-emerald-300">MANUAL PAPER LIVE</span><span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1.5 font-mono text-[10px] text-emerald-300">AUTO PAPER LIVE</span><span className="rounded-full border border-amber-400/25 bg-amber-400/10 px-3 py-1.5 font-mono text-[10px] text-amber-300">LIVE CAPITAL · BROKER SETUP</span></div></div>
   <h1 className="mt-6 max-w-5xl font-display text-[2.55rem] font-bold leading-[.98] sm:text-5xl md:text-7xl">READ THE <span className="text-cyan-300">CANDLE</span>. READ THE <span className="text-fuchsia-300">CROWD</span>.</h1>
   <p className="mt-5 max-w-4xl text-[15px] leading-7 text-slate-300">Use Misfit Trader free: live-market intelligence, real OHLC candles, event-market probabilities, manual paper trading and autonomous Misfit AI paper portfolios. Paid tiers are for deeper tooling and automation—not a gate to proving whether Trader is useful. Real capital still requires a verified brokerage account and explicit trading authority.</p>
   <div className="mt-6 flex flex-wrap gap-3"><a href="#candle-lab" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-cyan-300 px-4 py-3 font-mono text-xs font-bold text-black">USE TRADER FREE ↓</a><button onClick={buyAccess} disabled={checkoutLoading||access?.status==='active'} className="inline-flex min-h-12 items-center justify-center rounded-xl border border-fuchsia-300/35 bg-fuchsia-300/10 px-4 py-3 font-mono text-xs font-bold text-fuchsia-200 disabled:cursor-default disabled:border-emerald-300/30 disabled:bg-emerald-300/10 disabled:text-emerald-200">{access?.status==='active'?'FOUNDING SUPPORTER ACTIVE':checkoutLoading?'OPENING STRIPE…':'BACK THE FOUNDING BUILD · $10'}</button><button onClick={load} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/15 px-4 py-3 font-mono text-xs text-slate-300"><RefreshCw size={14} className={loading?'animate-spin':''}/>REFRESH SIGNAL</button><a href="/command" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-4 py-3 font-mono text-xs text-slate-300">FOUNDER COMMAND</a></div>
  </section>

  {error&&<div className="mt-4 rounded-2xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
  {notice&&<button onClick={()=>setNotice('')} className="mt-4 w-full rounded-2xl border border-cyan-400/20 bg-cyan-400/[.06] p-4 text-left text-sm text-cyan-100">{notice}<span className="float-right">×</span></button>}
  {access?.status==='active'&&<section className="mt-4 rounded-2xl border border-emerald-400/25 bg-emerald-400/[.05] p-4"><div className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-emerald-300">FOUNDING SUPPORTER VERIFIED</div><p className="mt-2 text-sm leading-6 text-slate-400">Signed Stripe payment evidence is stored in Misfit Cloud. {access.email_hint?`Receipt identity: ${access.email_hint}. `:''}Core Trader remains free. Founding Supporter status is separate from future subscription tiers, brokerage onboarding and trading authority.</p></section>}

  <TraderPlans onFounding={buyAccess} checkoutLoading={checkoutLoading} access={access}/>
  <ExecutionModes capitalMode={capitalMode} controlMode={controlMode} onSelect={selectMode}/>

  <section id="candle-lab" className="mt-5 rounded-3xl border border-cyan-400/20 bg-[linear-gradient(135deg,rgba(34,211,238,.06),rgba(168,85,247,.045),rgba(0,0,0,.95))] p-4 md:p-7">
   <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-cyan-300">CANDLE CHEAT LAB · LIVE OHLC</div><h2 className="mt-2 text-3xl font-bold">TradingView-style learning without the jargon wall.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Pick a market. Misfit labels the latest mechanical candle patterns, explains what traders usually watch next, and shows the actual price structure. A pattern is evidence—not a promise.</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><select value={chartAsset} onChange={e=>setChartAsset(e.target.value)} className="min-h-12 rounded-xl border border-white/10 bg-black px-3 text-sm">{assets.length?assets.map(a=><option key={a.id} value={a.id}>{a.symbol} · {a.name}</option>):<><option value="bitcoin">BTC · Bitcoin</option><option value="ethereum">ETH · Ethereum</option><option value="solana">SOL · Solana</option></>}</select><button onClick={loadChart} className="min-h-12 rounded-xl border border-cyan-400/25 bg-cyan-400/10 px-3 font-mono text-xs text-cyan-200">{chartLoading?'LOADING…':'REFRESH CHART'}</button></div></div>
   <div className="mt-4 flex flex-wrap gap-2">{chartDays.map(d=><button key={d} onClick={()=>setDays(d)} className={`rounded-lg px-3 py-2 font-mono text-[10px] ${days===d?'bg-cyan-300 font-bold text-black':'border border-white/10 bg-black/50 text-slate-400'}`}>{d===1?'24H':`${d}D`}</button>)}</div>
   {chartError?<div className="mt-4 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">Chart feed: {chartError}</div>:<CandleChart candles={chart?.candles||[]} loading={chartLoading}/>} 
   <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{chart?.patterns?.length?chart.patterns.map(p=><PatternCard key={p.key} p={p}/>):<div className="rounded-2xl border border-white/10 bg-black/40 p-4 text-sm text-slate-500 md:col-span-2 xl:col-span-4">{chartLoading?'Scanning the latest candles…':'No headline pattern on the latest candle. That is useful too—do not force a setup that is not there.'}</div>}</div>
   <div className="mt-4 grid gap-3 sm:grid-cols-3"><Cheat name="DOJI" shape="＋" text="Open ≈ close. Indecision. Wait for range break."/><Cheat name="HAMMER" shape="⚑" text="Long lower wick. Rejection below. Confirm above high."/><Cheat name="ENGULFING" shape="▮▉" text="New body wraps prior body. Watch follow-through, not the label alone."/></div>
  </section>

  <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={BrainCircuit} label="FIELD EMOTION" value={loading?'…':emotion?.label?.toUpperCase()||'—'} sub={emotion?`${emotion.score}/100 composite`:'waiting'}/><Metric icon={Activity} label="REGIME" value={emotion?.regime?.replaceAll('_',' ').toUpperCase()||'—'} sub={emotion?`Fear/Greed ${emotion.fear_greed}`:'—'}/><Metric icon={Gauge} label="MANUAL EXPOSURE" value={`${exposure.toFixed(1)}%`} sub={`${money(posVal)} deployed`}/><Metric icon={WalletCards} label="MANUAL EQUITY" value={money(equity)} sub={`${pnl>=0?'+':''}${money(pnl)} P/L`} valueClass={tone(pnl)}/></section>

  <section className="mt-5 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-cyan-300">LIVE MARKET FIELD</div><h2 className="mt-1 text-2xl font-semibold">Market tape</h2><div className="mt-4 space-y-2">{assets.map(a=><button onClick={()=>setChartAsset(a.id)} key={a.symbol} className="grid w-full grid-cols-[1fr_auto_auto] gap-3 rounded-xl border border-white/8 bg-black/40 p-3 text-left"><div><b>{a.name}</b> <span className="font-mono text-xs text-cyan-300">{a.symbol}</span></div><div>{money(a.price_usd)}</div><div className={tone(a.change_24h_pct)}>{pct(a.change_24h_pct)}</div></button>)}</div></div><div className="rounded-3xl border border-cyan-400/20 bg-cyan-400/[.035] p-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-cyan-300">SIGNAL INTERPRETATION</div><h2 className="mt-3 text-2xl font-bold">{stance[0]}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{stance[1]}</p><div className="mt-4 grid grid-cols-2 gap-3"><Mini label="Breadth" value={emotion?`${Math.round(emotion.market_breadth*100)}%`:'—'}/><Mini label="Avg 24h" value={emotion?pct(emotion.avg_24h_change_pct):'—'}/><Mini label="Fear/Greed" value={emotion?.fear_greed??'—'}/><Mini label="Volatility" value={emotion?Number(emotion.avg_abs_24h_change_pct).toFixed(2):'—'}/></div></div></section>

  <section className="mt-5 rounded-3xl border border-violet-400/20 bg-violet-400/[.035] p-5 md:p-7"><div className="flex items-center gap-2 text-violet-300"><Trophy size={17}/><div className="font-mono text-[10px] uppercase tracking-[.16em]">AUTONOMOUS PAPER LEADERBOARD · 15-MIN CYCLES</div></div><h2 className="mt-2 text-2xl font-semibold">Same signal. Different bankrolls.</h2><p className="mt-2 text-sm text-slate-400">Misfit AI runs $100, $1,000, $2,500 and $10,000 virtual portfolios automatically. Results persist in Misfit Cloud. This is the PAPER + MISFIT AI lane; it cannot move real money.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{auto.map(a=><div key={a.account_key} className="rounded-2xl border border-white/10 bg-black/40 p-4"><div className="font-mono text-[10px] text-slate-500">START {money(a.starting_cash)}</div><div className="mt-2 text-2xl font-bold">{money(a.equity)}</div><div className={`mt-1 text-sm ${tone(a.pnl)}`}>{pct(a.return_pct)} · {money(a.pnl)}</div><div className="mt-3 text-xs text-slate-500">{a.trade_count} trades · cash {money(a.cash)}</div></div>)}</div></section>

  <section className="mt-5 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl border border-emerald-400/20 bg-emerald-400/[.035] p-5"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-emerald-300">MANUAL TRADING · PAPER</div><h2 className="mt-2 text-2xl font-semibold">Practice the setup</h2><p className="mt-2 text-xs leading-5 text-slate-500">You control the asset, size, buy and sell. These are virtual orders. The exact same manual interaction is the foundation for LIVE + MANUAL once a customer brokerage account is connected.</p><div className="mt-4 grid grid-cols-2 gap-3"><select value={ticket.symbol} onChange={e=>setTicket({...ticket,symbol:e.target.value})} className="min-h-12 rounded-xl border border-white/10 bg-black px-3">{assets.map(a=><option key={a.symbol}>{a.symbol}</option>)}</select><input type="number" value={ticket.usd} onChange={e=>setTicket({...ticket,usd:e.target.value})} className="min-h-12 rounded-xl border border-white/10 bg-black px-3"/></div><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>trade('buy')} className="min-h-14 rounded-xl bg-emerald-300 font-bold text-black">PAPER BUY</button><button onClick={()=>trade('sell')} className="min-h-14 rounded-xl border border-red-400/30 bg-red-400/10 font-bold text-red-200">PAPER SELL</button></div></div><div className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center gap-2"><History size={16} className="text-cyan-300"/><h2 className="text-xl font-semibold">Manual paper portfolio</h2></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Cash" value={money(paper.cash)}/><Mini label="Positions" value={money(posVal)}/><Mini label="P/L" value={money(pnl)}/></div><div className="mt-4 space-y-2">{Object.entries(paper.positions||{}).length?Object.entries(paper.positions).map(([sym,p])=><div key={sym} className="rounded-xl border border-white/8 bg-black/40 p-3 text-sm"><b>{sym}</b> · {Number(p.qty).toFixed(6)} · {money(Number(p.qty)*(prices[sym]||p.last))}</div>):<div className="text-sm text-slate-600">No manual paper positions yet.</div>}</div></div></section>

  <PredictionCockpit sports={sports} preds={preds} source={feed?.prediction_markets?.source}/>

  <section className="mt-5 rounded-3xl border border-fuchsia-400/20 bg-fuchsia-400/[.035] p-5 md:flex md:items-center md:justify-between md:gap-8"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-fuchsia-300">FREE TRADER LIVE · FOUNDING SUPPORTER OPTIONAL</div><h2 className="mt-2 text-2xl font-bold">Use the product free. Back the founding build for $10.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Manual paper trading and Misfit AI paper portfolios are live without a paywall. The existing $10 Stripe purchase is retained as a one-time Founding Supporter entitlement—not the ceiling of Trader. Pro, AI and Elite subscriptions are being staged separately; none of them grant brokerage authority.</p></div><div className="mt-4 shrink-0 rounded-2xl border border-fuchsia-400/25 bg-black/40 px-6 py-4 text-center md:mt-0"><div className="font-mono text-[10px] text-slate-500">FOUNDING SUPPORTER</div><div className="mt-1 text-4xl font-black text-fuchsia-300">$10</div><button onClick={buyAccess} disabled={checkoutLoading||access?.status==='active'} className="mt-3 min-h-11 rounded-xl bg-fuchsia-300 px-4 font-mono text-[10px] font-bold text-black disabled:bg-emerald-300">{access?.status==='active'?'VERIFIED SUPPORTER':checkoutLoading?'OPENING…':'BACK WITH STRIPE'}</button></div></section>

  <BrokerActivation capitalMode={capitalMode} controlMode={controlMode}/>

  <section className="mt-5 rounded-3xl border border-cyan-400/15 bg-cyan-400/[.025] p-5"><div className="flex items-center gap-2 text-cyan-300"><ShieldCheck size={18}/><h2 className="text-xl font-semibold">Proof before pitch</h2></div><p className="mt-3 text-sm leading-7 text-slate-500">Patterns and event-market probabilities are evidence, not fortune telling. The proof is measurable: what appeared, what happened next, drawdown, hit rate, and whether a strategy beat simple benchmarks. No fake edge, guaranteed-return language, or protected GHOSBC/Soul Cipher internals are exposed.</p></section>
 </main><Footer/></div>
}

function TraderPlans({onFounding,checkoutLoading,access}){
 const plans=[
  {name:'FREE',status:'LIVE NOW',price:'$0',copy:'Live market field, candle lab, event-market intelligence, manual paper trading and base Misfit AI paper evidence.',live:true},
  {name:'PRO',status:'PLANNED',price:'SUBSCRIPTION',copy:'Deeper alerts, history, expanded feeds and performance tooling. Recurring Stripe plan is not live yet.'},
  {name:'MISFIT AI',status:'PLANNED',price:'SUBSCRIPTION',copy:'Deeper AI scoring, strategy tournament controls and advanced autonomous paper tooling. Recurring Stripe plan is not live yet.'},
  {name:'ELITE',status:'GOVERNED FUTURE',price:'SUBSCRIPTION',copy:'Advanced automation, API/webhooks and bounded live-AI capability only after brokerage, authority and risk gates pass.'}
 ];
 return <section className="mt-5 rounded-3xl border border-fuchsia-400/20 bg-[linear-gradient(135deg,rgba(34,211,238,.045),rgba(217,70,239,.05),rgba(0,0,0,.95))] p-5 md:p-7"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-fuchsia-300">FREE → PRO → MISFIT AI → ELITE</div><h2 className="mt-2 text-2xl font-semibold">Prove the edge first. Upsell the power.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">The free lane is real today. Paid subscription tiers are staged here so Trader has a product ladder, but they will not be sold until their Stripe products and actual feature entitlements are wired and verified.</p></div><button onClick={onFounding} disabled={checkoutLoading||access?.status==='active'} className="min-h-11 shrink-0 rounded-xl border border-fuchsia-300/30 bg-fuchsia-300/10 px-4 font-mono text-[10px] font-bold text-fuchsia-200 disabled:border-emerald-300/25 disabled:text-emerald-300">{access?.status==='active'?'FOUNDING SUPPORTER ✓':checkoutLoading?'OPENING…':'FOUNDING SUPPORTER · $10'}</button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{plans.map(p=><div key={p.name} className={`rounded-2xl border p-4 ${p.live?'border-cyan-300/30 bg-cyan-300/[.06]':'border-white/10 bg-black/40'}`}><div className="flex items-center justify-between gap-2"><b>{p.name}</b><span className={`rounded-full px-2 py-1 font-mono text-[8px] ${p.live?'bg-emerald-300/10 text-emerald-300':'bg-amber-300/10 text-amber-300'}`}>{p.status}</span></div><div className="mt-3 font-mono text-xs text-cyan-200">{p.price}</div><p className="mt-2 text-xs leading-5 text-slate-500">{p.copy}</p></div>)}</div></section>
}

function ExecutionModes({capitalMode,controlMode,onSelect}){
 const modes=[
  {capital:'paper',control:'manual',title:'PAPER + MANUAL',status:'LIVE NOW',copy:'You choose the asset, size, buy and sell. Virtual cash only.'},
  {capital:'paper',control:'ai',title:'PAPER + MISFIT AI',status:'LIVE NOW',copy:'Misfit AI runs autonomous virtual portfolios and records every decision.'},
  {capital:'live',control:'manual',title:'LIVE + MANUAL',status:'BROKER SETUP',copy:'You place the order. Requires your verified brokerage account, KYC and funding.'},
  {capital:'live',control:'ai',title:'LIVE + MISFIT AI',status:'GOVERNED GATE',copy:'Autonomous real-capital execution requires explicit authority, hard risk limits and kill switch.'}
 ];
 return <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.025] p-5 md:p-7"><div className="font-mono text-[10px] uppercase tracking-[.18em] text-cyan-300">EXECUTION MODE</div><h2 className="mt-2 text-2xl font-semibold">One Trader. Four lanes.</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">Paper and live capital are separate. Manual and Misfit AI control are separate. Selecting a live lane never grants authority or moves funds by itself.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{modes.map(m=>{const active=capitalMode===m.capital&&controlMode===m.control;const live=m.capital==='paper';return <button key={m.title} onClick={()=>onSelect(m.capital,m.control)} className={`min-w-0 rounded-2xl border p-4 text-left ${active?'border-cyan-300 bg-cyan-300/[.08]':'border-white/10 bg-black/35'}`}><div className="flex flex-wrap items-center justify-between gap-2"><b>{m.title}</b><span className={`rounded-full px-2 py-1 font-mono text-[9px] ${live?'bg-emerald-300/10 text-emerald-300':'bg-amber-300/10 text-amber-300'}`}>{m.status}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{m.copy}</p></button>})}</div></section>
}

function PredictionCockpit({sports,preds,source}){
 const [tab,setTab]=useState('sports');
 const items=(tab==='sports'?sports:preds)||[];
 const formatVolume=(n)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(n||0));
 const formatClose=(v)=>{if(!v)return'OPEN';const d=new Date(v);return Number.isNaN(d.getTime())?'OPEN':d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})};
 return <section className="mt-5 rounded-3xl border border-cyan-400/20 bg-[linear-gradient(135deg,rgba(34,211,238,.05),rgba(168,85,247,.045),rgba(0,0,0,.96))] p-5 md:p-7">
  <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-cyan-300">PREDICTION MARKET COCKPIT · {source||'KALSHI PUBLIC MARKET DATA'}</div><h2 className="mt-2 text-2xl font-semibold">Kalshi-style event intelligence, inside Misfit Trader.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Read live YES probabilities, volume and closing windows without leaving the Trader workflow. Sports and fights are filtered into their own lane. These are event contracts—not sportsbook point spreads—and Misfit does not place a wager or contract order yet.</p></div><a href="https://kalshi.com/browse" target="_blank" rel="noreferrer" className="inline-flex min-h-11 shrink-0 items-center justify-center rounded-xl border border-cyan-400/25 bg-cyan-400/10 px-4 font-mono text-[10px] font-bold text-cyan-200">OPEN KALSHI SOURCE</a></div>
  <div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>setTab('sports')} className={`min-h-12 rounded-xl border px-3 font-mono text-[10px] font-bold ${tab==='sports'?'border-cyan-300 bg-cyan-300 text-black':'border-white/10 bg-black/40 text-slate-400'}`}>SPORTS / FIGHTS · {sports?.length||0}</button><button onClick={()=>setTab('all')} className={`min-h-12 rounded-xl border px-3 font-mono text-[10px] font-bold ${tab==='all'?'border-fuchsia-300 bg-fuchsia-300 text-black':'border-white/10 bg-black/40 text-slate-400'}`}>ALL EVENT MARKETS · {preds?.length||0}</button></div>
  <div className="mt-4 grid gap-3 lg:grid-cols-2">{items.length?items.slice(0,16).map(m=><div key={m.ticker} className="min-w-0 rounded-2xl border border-white/10 bg-black/45 p-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="break-words text-sm font-semibold leading-5">{m.title}</div><div className="mt-1 break-all font-mono text-[9px] text-slate-600">{m.ticker}</div></div><div className="shrink-0 text-right"><div className="font-mono text-[9px] text-slate-600">YES</div><div className="text-2xl font-black text-cyan-300">{Number(m.yes_probability_pct||0).toFixed(1)}%</div></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-cyan-300" style={{width:`${Math.max(0,Math.min(100,Number(m.yes_probability_pct||0)))}%`}}/></div><div className="mt-3 grid grid-cols-2 gap-2"><Mini label="Volume" value={formatVolume(m.volume)}/><Mini label="Closes" value={formatClose(m.close_time)}/></div></div>):<div className="rounded-2xl border border-white/10 bg-black/40 p-5 text-sm text-slate-600 lg:col-span-2">No {tab==='sports'?'sports / fights':'prediction'} markets returned in this refresh.</div>}</div>
  <div className="mt-4 rounded-2xl border border-amber-400/20 bg-amber-400/[.045] p-4"><div className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-amber-300">SPORTSBOOK LANE · PROVIDER NOT CONNECTED</div><p className="mt-2 text-xs leading-5 text-slate-500">Misfit already has live Kalshi-style sports event contracts in the feed. Traditional sportsbook odds, betslips and wager execution are a separate provider integration and remain disconnected until a compliant provider rail is selected.</p></div>
 </section>
}

function BrokerActivation({capitalMode,controlMode}){
 const selected=capitalMode==='live';
 return <section className={`mt-5 rounded-3xl border p-5 ${selected?'border-amber-300/35 bg-amber-300/[.055]':'border-amber-400/20 bg-amber-400/[.035]'}`}><div className="flex items-center gap-2 text-amber-300"><LockKeyhole size={18}/><h2 className="text-xl font-semibold">Live-money activation</h2></div><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-emerald-300/10 px-2.5 py-1 font-mono text-[9px] text-emerald-300">PAPER MANUAL · LIVE</span><span className="rounded-full bg-emerald-300/10 px-2.5 py-1 font-mono text-[9px] text-emerald-300">PAPER AI · LIVE</span><span className="rounded-full bg-amber-300/10 px-2.5 py-1 font-mono text-[9px] text-amber-300">LIVE MANUAL · BROKER REQUIRED</span><span className="rounded-full bg-amber-300/10 px-2.5 py-1 font-mono text-[9px] text-amber-300">LIVE AI · AUTHORITY REQUIRED</span></div><p className="mt-3 text-sm leading-6 text-slate-400">{selected?`You selected LIVE + ${controlMode==='manual'?'MANUAL':'MISFIT AI'}. The interface is ready as a product lane, but no real order can be submitted until the customer brokerage rail is connected.`:'Real capital is a first-class Trader mode, but execution stays locked until the brokerage rail is actually connected.'}</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{['Customer sign-in + account binding','Broker KYC / account approval','Funding + buying-power sync','Server-side order authority','Max position + daily-loss rails','Kill switch + immutable audit'].map((x,i)=><div key={x} className="rounded-xl border border-white/8 bg-black/35 p-3"><div className="font-mono text-[9px] text-slate-600">GATE {i+1}</div><div className="mt-1 text-xs text-slate-400">{x}</div></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-600">Manual live execution activates before autonomous live execution. Product access or a Stripe payment never grants brokerage authority by itself.</p></section>
}

function CandleChart({candles,loading}){
 if(loading)return <div className="mt-4 flex h-72 items-center justify-center rounded-2xl border border-white/10 bg-black/60 font-mono text-xs text-cyan-300">LOADING LIVE OHLC…</div>;
 if(!candles.length)return <div className="mt-4 flex h-72 items-center justify-center rounded-2xl border border-white/10 bg-black/60 text-sm text-slate-600">No candle data returned.</div>;
 const data=candles.slice(-60),W=1000,H=380,pad=28,min=Math.min(...data.map(c=>Number(c.l))),max=Math.max(...data.map(c=>Number(c.h))),span=Math.max(max-min,1e-9),step=(W-pad*2)/Math.max(data.length,1),bodyW=Math.max(3,Math.min(11,step*.58)),y=v=>pad+(max-Number(v))/span*(H-pad*2);
 const last=data[data.length-1];
 return <div className="mt-4 overflow-hidden rounded-2xl border border-white/10 bg-black/70"><div className="flex items-center justify-between border-b border-white/8 px-4 py-3"><div className="font-mono text-[10px] text-slate-500">{data.length} OHLC CANDLES</div><div className={`font-mono text-xs ${Number(last.c)>=Number(last.o)?'text-emerald-300':'text-red-300'}`}>{money(last.c)}</div></div><svg viewBox={`0 0 ${W} ${H}`} className="h-[300px] w-full" role="img" aria-label="Live candlestick chart">{[0,.25,.5,.75,1].map((f,i)=><line key={i} x1={pad} x2={W-pad} y1={pad+f*(H-pad*2)} y2={pad+f*(H-pad*2)} stroke="rgba(148,163,184,.09)" strokeWidth="1"/>)}{data.map((c,i)=>{const x=pad+i*step+step/2,up=Number(c.c)>=Number(c.o),yo=y(c.o),yc=y(c.c),yh=y(c.h),yl=y(c.l),top=Math.min(yo,yc),bh=Math.max(2,Math.abs(yc-yo)),col=up?'#6ee7b7':'#fca5a5';return <g key={`${c.t}-${i}`}><line x1={x} x2={x} y1={yh} y2={yl} stroke={col} strokeWidth="1.7"/><rect x={x-bodyW/2} y={top} width={bodyW} height={bh} rx="1" fill={col}/></g>})}</svg><div className="grid grid-cols-4 border-t border-white/8 text-center font-mono text-[9px] text-slate-600"><span className="p-2">O {money(last.o)}</span><span className="p-2">H {money(last.h)}</span><span className="p-2">L {money(last.l)}</span><span className="p-2">C {money(last.c)}</span></div></div>
}
function PatternCard({p}){const cls=p.bias?.includes('bull')?'text-emerald-300':p.bias?.includes('bear')?'text-red-300':'text-amber-300';return <div className="rounded-2xl border border-white/10 bg-black/45 p-4"><div className="flex items-center justify-between gap-2"><b>{p.name}</b><span className={`font-mono text-[9px] uppercase ${cls}`}>{p.bias}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{p.meaning}</p><div className="mt-3 rounded-xl border border-white/8 bg-white/[.025] p-3 text-[11px] leading-5 text-slate-500"><b className="text-slate-300">Confirmation:</b> {p.confirm}</div></div>}
function Cheat({name,shape,text}){return <div className="rounded-2xl border border-white/10 bg-black/40 p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-cyan-400/20 bg-cyan-400/10 text-lg text-cyan-300">{shape}</div><div><div className="font-mono text-[10px] font-bold text-cyan-300">{name}</div><div className="mt-1 text-xs leading-5 text-slate-500">{text}</div></div></div></div>}
function Metric({icon:Icon,label,value,sub,valueClass=''}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500"><Icon size={14}/>{label}</div><div className={`mt-3 text-xl font-bold ${valueClass}`}>{value}</div><div className="mt-1 text-xs text-slate-600">{sub}</div></div>}
function Mini({label,value}){return <div className="min-w-0 rounded-xl border border-white/8 bg-black/40 p-3"><div className="font-mono text-[9px] uppercase text-slate-600">{label}</div><div className="mt-1 break-words text-sm font-semibold">{value}</div></div>}
