import { useEffect, useMemo, useState } from 'react';
import { Activity, BrainCircuit, LockKeyhole, Radar, RefreshCw, ShieldCheck, TrendingUp, WalletCards } from 'lucide-react';
import Navbar from '../components/Navbar.jsx';
import Footer from '../components/Footer.jsx';

const FEED='https://cibcxqrqiqvzpardbdrw.supabase.co/functions/v1/noop-probe';
const STORAGE='misfit-worldforge-paper-v1';
const starting={cash:100000,positions:{},trades:[]};
const money=(n)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<10?4:2}).format(Number(n||0));
const pct=(n)=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;

export default function WorldForge(){
  const [feed,setFeed]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const [paper,setPaper]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||starting}catch{return starting}});
  const [ticket,setTicket]=useState({symbol:'BTC',usd:1000});
  const load=async()=>{setLoading(true);setError('');try{const r=await fetch(FEED,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j?.error||'feed unavailable');setFeed(j)}catch(e){setError(e.message||'feed unavailable')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]); useEffect(()=>{localStorage.setItem(STORAGE,JSON.stringify(paper))},[paper]);
  const prices=useMemo(()=>Object.fromEntries((feed?.assets||[]).map(a=>[a.symbol,Number(a.price_usd||0)])),[feed]);
  const equity=useMemo(()=>paper.cash+Object.entries(paper.positions||{}).reduce((s,[sym,p])=>s+(Number(p.qty||0)*Number(prices[sym]||p.last||0)),0),[paper,prices]);
  const trade=(side)=>{const sym=ticket.symbol,price=prices[sym],usd=Math.max(1,Number(ticket.usd||0));if(!price)return;const qty=usd/price;setPaper(prev=>{const pos=prev.positions[sym]||{qty:0,cost:0,last:price};let cash=prev.cash,nextQty=pos.qty,nextCost=pos.cost;if(side==='buy'){if(usd>cash)return prev;cash-=usd;nextQty+=qty;nextCost+=usd}else{const sellQty=Math.min(qty,nextQty);if(sellQty<=0)return prev;const proceeds=sellQty*price;cash+=proceeds;const avg=nextQty?nextCost/nextQty:0;nextQty-=sellQty;nextCost=Math.max(0,nextCost-sellQty*avg)}const positions={...prev.positions,[sym]:{qty:nextQty,cost:nextCost,last:price}};if(nextQty<1e-12)delete positions[sym];const trades=[{id:Date.now(),side,symbol:sym,usd,price,emotion:feed?.emotion?.label,score:feed?.emotion?.score,at:new Date().toISOString()},...(prev.trades||[])].slice(0,30);return{...prev,cash,positions,trades}})};
  const assets=feed?.assets||[]; const emotion=feed?.emotion;
  return <div className="min-h-screen bg-black text-white"><Navbar/><main className="mx-auto max-w-7xl px-5 pb-24 pt-28">
    <section className="overflow-hidden rounded-[2rem] border border-cyan-400/20 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,.16),transparent_35%),radial-gradient(circle_at_bottom_right,rgba(168,85,247,.15),transparent_36%),linear-gradient(135deg,#071018,#000)] p-6 md:p-10">
      <div className="flex flex-wrap items-center justify-between gap-3"><div className="inline-flex items-center gap-2 rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 font-mono text-[10px] uppercase tracking-[.18em] text-cyan-300"><Radar size={13}/> WorldForge · emotional market radar</div><div className="flex gap-2"><span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1 font-mono text-[10px] text-emerald-300">PAPER LIVE</span><span className="rounded-full border border-amber-400/25 bg-amber-400/10 px-3 py-1 font-mono text-[10px] text-amber-300">REAL MONEY GATED</span></div></div>
      <h1 className="mt-6 max-w-5xl font-display text-4xl font-bold tracking-tight md:text-7xl">TRADE THE <span className="text-cyan-300">HUMAN FIELD</span>, NOT JUST THE CANDLE.</h1>
      <p className="mt-5 max-w-4xl text-base leading-7 text-slate-300">WorldForge turns crowd fear/greed, market breadth, momentum and volatility into an emotion-first market regime. The public layer exposes explainable signals only. Protected GHOSBC / Soul Cipher internals remain sealed.</p>
      <div className="mt-7 flex flex-wrap gap-3"><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-3 font-mono text-xs font-bold text-black"><RefreshCw size={14} className={loading?'animate-spin':''}/>REFRESH FIELD</button><a href="/command" className="rounded-xl border border-white/15 px-4 py-3 font-mono text-xs text-slate-300">FOUNDER COMMAND</a></div>
    </section>

    {error&&<div className="mt-5 rounded-2xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
    <section className="mt-6 grid gap-4 md:grid-cols-4">
      <Metric icon={BrainCircuit} label="FIELD EMOTION" value={loading?'…':emotion?.label?.toUpperCase()||'—'} sub={emotion?`${emotion.score}/100 composite`:'waiting for feed'}/>
      <Metric icon={Activity} label="REGIME" value={emotion?.regime?.replaceAll('_',' ').toUpperCase()||'—'} sub={emotion?`Fear/Greed ${emotion.fear_greed}`:'—'}/>
      <Metric icon={TrendingUp} label="BREADTH" value={emotion?`${Math.round(emotion.market_breadth*100)}%`:'—'} sub={emotion?`${pct(emotion.avg_24h_change_pct)} avg 24h`:'assets green'}/>
      <Metric icon={WalletCards} label="PAPER EQUITY" value={money(equity)} sub={`${money(paper.cash)} virtual cash`}/>
    </section>

    <section className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <div className="rounded-3xl border border-white/10 bg-white/[.025] p-5 md:p-7"><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-semibold">Live market field</h2><span className="font-mono text-[10px] text-slate-500">{feed?.observed_at?new Date(feed.observed_at).toLocaleString():'loading'}</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-[10px] uppercase tracking-widest text-slate-500"><tr><th className="pb-3">Asset</th><th>Price</th><th>24h</th><th>Volume</th><th>Market cap</th></tr></thead><tbody>{assets.map(a=><tr key={a.symbol} className="border-t border-white/7"><td className="py-4 font-semibold">{a.name} <span className="font-mono text-xs text-cyan-300">{a.symbol}</span></td><td>{money(a.price_usd)}</td><td className={Number(a.change_24h_pct)>=0?'text-emerald-300':'text-red-300'}>{pct(a.change_24h_pct)}</td><td>{money(a.volume_24h_usd)}</td><td>{money(a.market_cap_usd)}</td></tr>)}</tbody></table></div></div>
      <div className="rounded-3xl border border-emerald-400/20 bg-emerald-400/[.035] p-5 md:p-7"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-emerald-300">Paper execution sandbox</div><h2 className="mt-2 font-display text-2xl font-semibold">Simulate the signal</h2><p className="mt-2 text-sm leading-6 text-slate-500">Virtual money only. No exchange, wallet or broker order is created.</p><label className="mt-5 block font-mono text-[10px] text-slate-500">ASSET</label><select value={ticket.symbol} onChange={e=>setTicket({...ticket,symbol:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black p-3">{assets.map(a=><option key={a.symbol}>{a.symbol}</option>)}</select><label className="mt-4 block font-mono text-[10px] text-slate-500">VIRTUAL NOTIONAL USD</label><input type="number" min="1" value={ticket.usd} onChange={e=>setTicket({...ticket,usd:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black p-3"/><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>trade('buy')} className="rounded-xl bg-emerald-300 p-3 font-bold text-black">PAPER BUY</button><button onClick={()=>trade('sell')} className="rounded-xl border border-red-400/30 bg-red-400/10 p-3 font-bold text-red-200">PAPER SELL</button></div><button onClick={()=>setPaper(starting)} className="mt-3 w-full rounded-xl border border-white/10 p-3 font-mono text-[10px] text-slate-500">RESET $100K SANDBOX</button></div>
    </section>

    <section className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><h2 className="font-display text-xl font-semibold">Paper positions</h2><div className="mt-4 space-y-2">{Object.entries(paper.positions||{}).length===0?<p className="text-sm text-slate-600">No paper positions yet.</p>:Object.entries(paper.positions).map(([sym,p])=>{const px=prices[sym]||p.last;const value=p.qty*px;const pnl=value-p.cost;return <div key={sym} className="grid grid-cols-4 gap-2 rounded-xl border border-white/8 bg-black/40 p-3 text-sm"><b>{sym}</b><span>{p.qty.toFixed(6)}</span><span>{money(value)}</span><span className={pnl>=0?'text-emerald-300':'text-red-300'}>{money(pnl)}</span></div>})}</div></div><div className="rounded-3xl border border-amber-400/20 bg-amber-400/[.035] p-6"><div className="flex items-center gap-2 text-amber-300"><LockKeyhole size={18}/><h2 className="font-display text-xl font-semibold">Real-money execution</h2></div><p className="mt-4 text-sm leading-6 text-slate-400">Architecture-ready, intentionally disabled. Activation requires an explicit owner decision plus broker/exchange selection, maximum position size, daily loss limit, leverage policy, kill switch and audit rules. WorldForge v1 cannot place a real order.</p><div className="mt-4 rounded-xl border border-white/10 bg-black/40 p-4 font-mono text-xs text-slate-500">REAL_MONEY_ENABLED=false<br/>LEVERAGE_ENABLED=false<br/>OWNER_APPROVAL_REQUIRED=true<br/>KILL_SWITCH=true</div></div></section>

    <section className="mt-6 rounded-3xl border border-cyan-400/15 bg-cyan-400/[.025] p-6"><div className="flex items-center gap-2 text-cyan-300"><ShieldCheck size={18}/><h2 className="font-display text-xl font-semibold">What the signal is — and is not</h2></div><p className="mt-4 max-w-5xl text-sm leading-7 text-slate-500">This first live layer measures observable crowd/market emotion using public data. It does not claim to predict prices, does not expose proprietary Soul Cipher/GHOSBC mappings, and is not investment advice. Next layers can add news/social narrative, on-chain flows, geographic emotional signals, governed strategy testing and broker overlays while preserving a hard separation between signal generation and real-money authority.</p></section>
  </main><Footer/></div>
}
function Metric({icon:Icon,label,value,sub}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.15em] text-slate-500"><Icon size={14}/>{label}</div><div className="mt-3 text-xl font-bold text-white">{value}</div><div className="mt-1 text-xs text-slate-600">{sub}</div></div>}
