import { useEffect, useMemo, useState } from 'react';
import { Activity, Coins, Gem, Landmark, Network, ShieldCheck } from 'lucide-react';

const FEED='https://cibcxqrqiqvzpardbdrw.supabase.co/functions/v1/noop-probe';
const METALS=['GLD','SLV','PAXG','XAUT','KAG'];
const TREASURIES=['BIL','SHY','IEF','TLT'];
const money=(n)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Math.abs(Number(n||0))<10?4:2}).format(Number(n||0));
const signed=(n)=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const short=(s='')=>s?`${s.slice(0,6)}…${s.slice(-4)}`:'—';
const pnl=(n)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(Number(n||0));

export default function TraderNetworkLane(){
  const [feed,setFeed]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);setError('');try{const r=await fetch(FEED,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j?.error||'feed unavailable');setFeed(j)}catch(e){setError(e.message||'feed unavailable')}finally{setLoading(false)}};
  useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
  const bySymbol=useMemo(()=>Object.fromEntries((feed?.assets||[]).map(a=>[a.symbol,a])),[feed]);
  const metals=METALS.map(s=>bySymbol[s]).filter(Boolean),treasuries=TREASURIES.map(s=>bySymbol[s]).filter(Boolean);
  const hyper=feed?.trader_intelligence?.hyperliquid?.top||[],poly=feed?.trader_intelligence?.polymarket?.overall||[];

  return <section id="network-intelligence" className="mt-5 overflow-hidden rounded-3xl border border-amber-300/20 bg-[radial-gradient(circle_at_8%_0%,rgba(250,204,21,.12),transparent_34%),radial-gradient(circle_at_92%_18%,rgba(34,211,238,.11),transparent_34%),rgba(255,255,255,.018)] p-5 md:p-7">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-amber-300/25 bg-amber-300/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.18em] text-amber-200"><Network size={14}/> MISFIT TRADER · NETWORK INTELLIGENCE</div><h2 className="mt-3 text-3xl font-black sm:text-4xl">METALS. TREASURIES. <span className="text-cyan-300">SMART MONEY WATCH.</span></h2><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-400">One research layer across traditional markets, tokenized metals and public trader leaderboards. Misfit watches the evidence automatically; it does not blindly copy another trader or grant real-money authority.</p></div><button onClick={load} className="inline-flex min-h-11 w-fit items-center gap-2 rounded-xl border border-white/10 bg-black/40 px-4 font-mono text-[10px] text-slate-400"><Activity size={13} className={loading?'animate-pulse':''}/>{loading?'REFRESHING…':'REFRESH INTELLIGENCE'}</button></div>

    {error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-200">Network intelligence: {error}</div>}

    <div className="mt-5 grid gap-4 xl:grid-cols-2">
      <div className="rounded-2xl border border-amber-300/15 bg-black/45 p-4"><div className="flex items-center gap-2 font-mono text-[10px] font-bold text-amber-200"><Gem size={14}/> GOLD + SILVER · TRADITIONAL + CRYPTO</div><p className="mt-2 text-xs leading-5 text-slate-600">Traditional exposure uses listed metal ETFs. Crypto exposure uses tokenized-metal assets carried in the same paper-trading universe.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{metals.length?metals.map(a=><Asset key={a.symbol} a={a}/>):<Empty text="Waiting for metal prices…"/>}</div></div>
      <div className="rounded-2xl border border-cyan-300/15 bg-black/45 p-4"><div className="flex items-center gap-2 font-mono text-[10px] font-bold text-cyan-200"><Landmark size={14}/> WAR BONDS / SOVEREIGN DEFENSE MACRO</div><p className="mt-2 text-xs leading-5 text-slate-600">A Misfit macro lens over real tradable U.S. Treasury ETFs from bills through long bonds. It is not a newly invented security or a claim that a special modern “war bond” exists.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{treasuries.length?treasuries.map(a=><Asset key={a.symbol} a={a}/>):<Empty text="Waiting for Treasury prices…"/>}</div></div>
    </div>

    <div className="mt-4 rounded-2xl border border-fuchsia-300/15 bg-black/45 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 font-mono text-[10px] font-bold text-fuchsia-200"><Coins size={14}/> TOP-TRADER AUTOPILOT · PUBLIC LEADERBOARDS</div><span className="w-fit rounded-full border border-amber-300/20 bg-amber-300/[.06] px-2 py-1 font-mono text-[8px] text-amber-200">RESEARCH ONLY · NO AUTO-COPY</span></div><p className="mt-2 text-xs leading-5 text-slate-600">Every 15 minutes Misfit refreshes connected public leaderboards and records the snapshot in Misfit Cloud. Past P&amp;L is evidence about a trader’s history—not a forecast.</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><TraderList title="HYPERLIQUID" rows={hyper.slice(0,6)} kind="hyper"/><TraderList title="POLYMARKET" rows={poly.slice(0,6)} kind="poly"/></div><div className="mt-3 font-mono text-[9px] leading-5 text-slate-700">CONNECTED NOW: HYPERLIQUID + POLYMARKET · KALSHI MARKET INTELLIGENCE · BINANCE / BYBIT / ETORO ADAPTERS ARE RESEARCH, NOT CLAIMED LIVE.</div></div>

    <div className="mt-4 rounded-2xl border border-emerald-300/15 bg-emerald-300/[.025] p-4"><div className="flex items-center gap-2 font-mono text-[10px] font-bold text-emerald-200"><ShieldCheck size={14}/> TOKENIZATION READINESS · NATIVE TOKEN STILL GATED</div><div className="mt-3 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{['IDENTITY','REPUTATION','USAGE RECEIPTS','MACHINE PAYMENTS','GOVERNANCE','TOKEN GRADUATION'].map((x,i)=><div key={x} className="rounded-xl border border-white/8 bg-black/35 p-3"><div className="font-mono text-[8px] text-slate-700">{String(i+1).padStart(2,'0')}</div><b className="mt-1 block text-[10px] text-slate-300">{x}</b></div>)}</div><p className="mt-3 text-xs leading-5 text-slate-600">Misfit is building measurable utility first: identity, reputation, credits, receipts, audit and machine-paid services. A transferable native token does not launch until the graduation gates prove it solves a real network problem better than stablecoins plus credits.</p></div>
  </section>
}

function Asset({a}){const crypto=a.asset_type==='crypto';return <div className="min-w-0 rounded-xl border border-white/8 bg-white/[.025] p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><b className="text-sm">{a.symbol}</b><div className="mt-1 truncate text-[10px] text-slate-600">{a.name}</div></div><span className={`shrink-0 rounded-full px-2 py-1 font-mono text-[7px] ${crypto?'bg-fuchsia-300/10 text-fuchsia-200':'bg-cyan-300/10 text-cyan-200'}`}>{crypto?'CRYPTO':'TRAD'}</span></div><div className="mt-3 flex items-end justify-between gap-2"><b className="text-sm text-slate-200">{money(a.price_usd)}</b><span className={`font-mono text-[9px] ${Number(a.change_24h_pct)>=0?'text-emerald-300':'text-red-300'}`}>{signed(a.change_24h_pct)}</span></div></div>}
function TraderList({title,rows,kind}){return <div className="min-w-0 rounded-xl border border-white/8 bg-white/[.02] p-3"><div className="font-mono text-[9px] font-bold text-slate-400">{title} · TOP PUBLIC RESULTS</div><div className="mt-2 space-y-2">{rows.length?rows.map((r,i)=><div key={`${r.address}-${i}`} className="grid grid-cols-[auto_1fr_auto] items-center gap-2 rounded-lg border border-white/5 bg-black/35 px-2 py-2"><span className="font-mono text-[9px] text-slate-700">#{r.misfit_rank||r.rank||i+1}</span><div className="min-w-0"><div className="truncate text-[10px] text-slate-300">{r.display_name||r.username||short(r.address)}</div><div className="font-mono text-[8px] text-slate-700">{kind==='hyper'?`EQUITY ${pnl(r.account_value)}`:`VOL ${pnl(r.volume)}`}</div></div><div className="text-right"><div className={`font-mono text-[9px] ${Number(kind==='hyper'?r.month?.pnl:r.pnl)>=0?'text-emerald-300':'text-red-300'}`}>{pnl(kind==='hyper'?r.month?.pnl:r.pnl)}</div><div className="font-mono text-[7px] text-slate-700">{kind==='hyper'?'MONTH PNL':'MONTH PNL'}</div></div></div>):<Empty text="Source unavailable this cycle."/>}</div></div>}
function Empty({text}){return <div className="rounded-xl border border-dashed border-white/10 p-4 text-xs text-slate-600 sm:col-span-2">{text}</div>}
