import { useEffect, useMemo, useState } from 'react';
import { Activity, BrainCircuit, Crosshair, RefreshCw, ShieldCheck, Trophy } from 'lucide-react';

const RPC='https://cibcxqrqiqvzpardbdrw.supabase.co/rest/v1/rpc/misfit_trader_shadow_public';
const PUBLIC_KEY='sb_publishable_X-bcgz-3xMIgNZ4rYmAjZA_QNUb69hU';
const money=(n)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
const signed=(n)=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const short=(s='')=>s?`${s.slice(0,6)}…${s.slice(-4)}`:'—';
const compact=(n)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(n||0));

export default function TraderShadowLane(){
  const [state,setState]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const r=await fetch(RPC,{method:'POST',headers:{'Content-Type':'application/json',apikey:PUBLIC_KEY},body:'{}',cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j?.message||j?.error||'shadow strategies unavailable');setState(j)}catch(e){setError(e?.message||'shadow strategies unavailable')}finally{setLoading(false)}};
  useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
  const strategies=useMemo(()=>[...(state?.strategies||[])].sort((a,b)=>Number(b.return_pct||0)-Number(a.return_pct||0)),[state]);
  const scores=state?.top_trader_scores||[],trades=state?.recent_shadow_trades||[],positionConsensus=state?.position_consensus||{},consensusRows=positionConsensus?.consensus||[];

  return <section id="shadow-strategies" className="mt-5 overflow-hidden rounded-3xl border border-fuchsia-300/20 bg-[radial-gradient(circle_at_10%_0%,rgba(217,70,239,.12),transparent_30%),radial-gradient(circle_at_90%_15%,rgba(34,211,238,.10),transparent_32%),rgba(255,255,255,.018)] p-5 md:p-7">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-fuchsia-300/25 bg-fuchsia-300/[.07] px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.18em] text-fuchsia-200"><BrainCircuit size={14}/> MISFIT TRADER · SHADOW STRATEGY TOURNAMENT</div><h2 className="mt-3 text-3xl font-black sm:text-4xl">LET THE STRATEGIES <span className="text-cyan-300">PROVE THEMSELVES.</span></h2><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-400">Independent $10K paper portfolios rebalance every 15 minutes from the same market evidence. Misfit records equity, return, drawdown and every trade so weak strategies can be demoted instead of protected by a good story.</p></div><button onClick={load} className="inline-flex min-h-11 w-fit items-center gap-2 rounded-xl border border-white/10 bg-black/40 px-4 font-mono text-[10px] text-slate-400"><RefreshCw size={13} className={loading?'animate-spin':''}/>{loading?'REFRESHING…':'REFRESH TOURNAMENT'}</button></div>
    {error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-200">Shadow engine: {error}</div>}

    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{strategies.length?strategies.map((s,i)=><StrategyCard key={s.strategy_key} s={s} rank={i+1}/>):<Empty text="Waiting for the first shadow-strategy cycle…"/>}</div>

    <div className="mt-4 rounded-2xl border border-violet-300/15 bg-black/45 p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 font-mono text-[10px] font-bold text-violet-200"><Crosshair size={14}/> LIVE POSITION CONSENSUS · HYPERLIQUID</div><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-600">Misfit asks the public clearinghouseState endpoint what the scored traders are actually holding now. A leaderboard winner with no open position contributes no directional vote.</p></div><span className="w-fit rounded-full border border-emerald-300/15 bg-emerald-300/[.05] px-2.5 py-1 font-mono text-[8px] text-emerald-200">PUBLIC POSITION ADAPTER LIVE</span></div>
      <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Requested" value={String(positionConsensus?.requested_traders??'—')}/><Mini label="Processed" value={String(positionConsensus?.processed_traders??'—')}/><Mini label="Actually active" value={String(positionConsensus?.active_traders??'—')}/><Mini label="Trade gate" value={consensusRows.some(x=>x.eligible)?'ELIGIBLE SIGNAL':'HOLD / INSUFFICIENT' } cls={consensusRows.some(x=>x.eligible)?'text-emerald-300':'text-amber-300'}/></div>
      <div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{consensusRows.length?consensusRows.map(c=><ConsensusRow key={c.symbol} c={c}/>):<Empty text="No open positions found in the current scored trader set."/>}</div>
      <p className="mt-3 font-mono text-[8px] leading-4 text-slate-700">ELIGIBILITY REQUIRES ≥3 INDEPENDENT ACTIVE TRADERS + ≥45% CONFIDENCE. POSITION SIZE IS CAPPED IN THE WEIGHTING SO ONE WHALE CANNOT BECOME “CONSENSUS.” NEGATIVE CONSENSUS REDUCES SPOT-PAPER EXPOSURE; IT DOES NOT OPEN A SHORT.</p>
    </div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.08fr_.92fr]">
      <div className="rounded-2xl border border-cyan-300/15 bg-black/45 p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 font-mono text-[10px] font-bold text-cyan-200"><Crosshair size={14}/> TRADER INTELLIGENCE SCORES</div><span className="rounded-full border border-white/10 px-2 py-1 font-mono text-[8px] text-slate-600">NO BLIND AUTO-COPY</span></div><p className="mt-2 text-xs leading-5 text-slate-600">Scores use public performance evidence. Hyperliquid current positions are now checked separately; drawdown and hit rate remain unavailable unless a source exposes them.</p><div className="mt-3 space-y-2">{scores.slice(0,10).map((r,i)=><ScoreRow key={`${r.platform}-${r.trader_key}-${i}`} r={r} rank={i+1}/>)}</div></div>
      <div className="rounded-2xl border border-amber-300/15 bg-black/45 p-4"><div className="flex items-center gap-2 font-mono text-[10px] font-bold text-amber-200"><Activity size={14}/> RECENT SHADOW EXECUTION</div><p className="mt-2 text-xs leading-5 text-slate-600">These are autonomous virtual-money trades only. Real capital and copy trading remain separately gated.</p><div className="mt-3 space-y-2">{trades.slice(0,10).map((t,i)=><TradeRow key={`${t.created_at}-${t.strategy_key}-${i}`} t={t}/>)}</div></div>
    </div>

    <div className="mt-4 rounded-2xl border border-emerald-300/15 bg-emerald-300/[.025] p-4"><div className="flex items-start gap-3"><ShieldCheck size={16} className="mt-0.5 shrink-0 text-emerald-300"/><div><div className="font-mono text-[10px] font-bold text-emerald-200">EVIDENCE GATE</div><p className="mt-2 text-xs leading-5 text-slate-600">Top-Trader Consensus may trade only when multiple scored traders independently hold the same direction with sufficient confidence. Current public scores and positions are research evidence, not advice and not proof of future performance.</p></div></div></div>
  </section>
}

function StrategyCard({s,rank}){const positive=Number(s.return_pct)>=0,positions=Object.keys(s.positions||{});const waiting=s.strategy_key==='top_trader_consensus_v1'&&Number(s.trade_count||0)===0;return <div className="min-w-0 rounded-2xl border border-white/10 bg-black/45 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-mono text-[9px] text-slate-700">#{rank} · PAPER STRATEGY</div><h3 className="mt-1 truncate text-base font-bold text-white">{s.label}</h3></div><Trophy size={15} className={rank===1?'text-amber-300':'text-slate-700'}/></div><div className="mt-4 grid grid-cols-2 gap-2"><Mini label="Equity" value={money(s.equity)}/><Mini label="Return" value={signed(s.return_pct)} cls={positive?'text-emerald-300':'text-red-300'}/><Mini label="Max DD" value={signed(s.max_drawdown_pct)}/><Mini label="Trades" value={String(s.trade_count||0)}/></div><div className="mt-3 flex flex-wrap gap-1.5">{waiting?<span className="rounded-full border border-amber-300/20 bg-amber-300/[.06] px-2 py-1 font-mono text-[8px] text-amber-200">CONSENSUS GATE HOLDING</span>:positions.length?positions.slice(0,6).map(x=><span key={x} className="rounded-full border border-white/8 px-2 py-1 font-mono text-[8px] text-slate-500">{x}</span>):<span className="font-mono text-[8px] text-slate-700">100% CASH</span>}</div><p className="mt-3 text-[11px] leading-5 text-slate-600">{s.description}</p></div>}
function ConsensusRow({c}){const net=Number(c.raw_net_consensus||0),eligible=Boolean(c.eligible);return <div className={`rounded-xl border p-3 ${eligible?'border-emerald-300/20 bg-emerald-300/[.035]':'border-white/8 bg-white/[.02]'}`}><div className="flex items-start justify-between gap-3"><div><b className="text-sm text-white">{c.symbol}</b><div className="mt-1 font-mono text-[8px] uppercase text-slate-700">{c.long_traders||0} LONG · {c.short_traders||0} SHORT · {c.active_traders||0} ACTIVE</div></div><span className={`rounded-full px-2 py-1 font-mono text-[8px] ${eligible?'bg-emerald-300/10 text-emerald-200':'bg-amber-300/10 text-amber-200'}`}>{eligible?'ELIGIBLE':'HOLD'}</span></div><div className="mt-3 grid grid-cols-3 gap-2"><Mini label="Net" value={`${net>=0?'+':''}${(net*100).toFixed(0)}%`} cls={net>0?'text-emerald-300':net<0?'text-red-300':'text-slate-300'}/><Mini label="Confidence" value={`${(Number(c.confidence||0)*100).toFixed(0)}%`}/><Mini label="Observed" value={`$${compact(c.observed_notional)}`}/></div></div>}
function ScoreRow({r,rank}){const name=r.display_name||short(r.trader_key),open=Array.isArray(r.current_positions)?r.current_positions.length:0;return <div className="grid grid-cols-[auto_1fr_auto] items-center gap-3 rounded-xl border border-white/7 bg-white/[.02] px-3 py-2"><span className="font-mono text-[9px] text-slate-700">#{rank}</span><div className="min-w-0"><div className="truncate text-[11px] text-slate-300">{name}</div><div className="font-mono text-[8px] uppercase text-slate-700">{r.platform}{r.platform==='Hyperliquid'?` · ${open} OPEN`:''}</div></div><div className="text-right"><div className="text-lg font-black text-cyan-300">{Number(r.score||0).toFixed(1)}</div><div className="font-mono text-[7px] text-slate-700">/100</div></div></div>}
function TradeRow({t}){return <div className="rounded-xl border border-white/7 bg-white/[.02] px-3 py-2"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-[10px] text-slate-400">{String(t.strategy_key||'').replaceAll('_',' ')}</div><div className="mt-1 font-mono text-[8px] text-slate-700">{String(t.rationale||'').slice(0,80)}</div></div><div className="shrink-0 text-right"><div className={`font-mono text-[9px] ${t.side==='buy'?'text-emerald-300':'text-red-300'}`}>{String(t.side||'').toUpperCase()} {t.symbol}</div><div className="font-mono text-[8px] text-slate-600">{money(t.notional_usd)}</div></div></div></div>}
function Mini({label,value,cls=''}){return <div className="min-w-0 rounded-xl border border-white/7 bg-white/[.02] p-2.5"><div className="font-mono text-[8px] uppercase text-slate-700">{label}</div><div className={`mt-1 break-words text-sm font-bold ${cls}`}>{value}</div></div>}
function Empty({text}){return <div className="rounded-xl border border-dashed border-white/10 p-4 text-xs text-slate-600 sm:col-span-2 xl:col-span-3">{text}</div>}
